// scenarios.jsx — Data for all 14 scenario scripts.
// Each scenario has: id, p (P-NN), title, category, summary, color, steps[].
// Step kinds: bot · user · divider · room · pill-room · carousel · quick-replies ·
//             info-card · gift-card · app-screen · ticket-card · rsvp-card ·
//             open-sheet · close-sheet · flow-submitted · wait

(function () {

const ROOMS = {
  tribbos: {
    id: 'r-tribbos', coworking: 'Tribbos Coworking',
    name: 'sala de reunião 02', capacity: 5, credits: 7,
    image: 'assets/room-1.svg',
    date: '16/05/2026', inicio: '10:00', fim: '17:00',
    address: 'Av. Marechal Floriano Peixoto, 720 — Casarão Histórico, Centro',
    amenities: 'Wi-Fi, Café, Ar condicionado',
  },
  vila: {
    id: 'r-vila', coworking: 'Vila Olímpia Hub',
    name: 'sala criativa 04', capacity: 6, credits: 8.5,
    image: 'assets/room-2.svg',
    date: '16/05/2026', inicio: '09:00', fim: '13:00',
    address: 'R. Funchal, 418 — Vila Olímpia, São Paulo',
    amenities: 'Wi-Fi, Café, Projetor, Lousa',
  },
  itaim: {
    id: 'r-itaim', coworking: 'WorkBricks Itaim',
    name: 'sala executiva', capacity: 8, credits: 9,
    image: 'assets/room-3.svg',
    date: '16/05/2026', inicio: '14:00', fim: '18:00',
    address: 'R. Leopoldo Couto de Magalhães Jr., 700 — Itaim Bibi',
    amenities: 'Wi-Fi, Café, TV 65", Videoconferência',
  },
  pinheiros: {
    id: 'r-pinh', coworking: 'Hub Pinheiros',
    name: 'sala 01', capacity: 5, credits: 7.5,
    image: 'assets/room-1.svg',
    date: '16/05/2026', inicio: '11:00', fim: '15:00',
    address: 'R. dos Pinheiros, 498 — Pinheiros, São Paulo',
    amenities: 'Wi-Fi, Café, Ar condicionado',
  },
};

const SCENARIOS = [
  /* ─────────── P-01 — Check-in proativo via deeplink ─────────── */
  {
    id: 'p01', p: 'P-01',
    title: 'Check-in proativo',
    category: 'Pré-reunião',
    summary: '15 min antes, deeplink que abre o app e tenta check-in automático (geofence + BLE).',
    color: '#81c42b',
    startTime: { h: 9, m: 44 },
    steps: [
      { kind: 'divider', label: 'Hoje' },
      { kind: 'bot', typing: 900, text: 'Sua reunião na **Tribbos Coworking** começa em 15 min 👋\n\nToque pra fazer seu **check-in** direto no app — vai automático assim que você chegar.' },
      { kind: 'info-card', delay: 400,
        title: '↗ Fazer check-in no app',
        lines: [],
        accent: 'var(--chat-link)',
      },
      { kind: 'user', delay: 1500, text: '[ toca em "Fazer check-in" ]' },
      { kind: 'divider', delay: 600, label: '↗ abrindo app Woba…', color: 'link' },
      { kind: 'app-screen', delay: 800,
        title: 'Check-in · sala 02',
        lines: ['Verificando localização…', 'Procurando beacon…'],
        success: '✓ Check-in automático',
      },
      { kind: 'bot', typing: 1000, delay: 1500, text: 'Tudo certo, check-in feito ✅\n\nAproveite a reunião. Te procuro de novo no fim, ok?' },
    ],
  },

  /* ─────────── P-02 — Huddle SOS ─────────── */
  {
    id: 'p02', p: 'P-02',
    title: 'Huddle SOS — sala agora',
    category: 'Reserva expressa',
    summary: '"Preciso de sala agora." Card único, sem Flow, confirmação em 1 toque.',
    color: '#fe8c14',
    startTime: { h: 14, m: 30 },
    steps: [
      { kind: 'user', text: 'preciso de uma sala agora pra 4 pessoas' },
      { kind: 'bot', typing: 900, text: 'Bora resolver 💨\n\nAchei a **mais perto disponível agora**:' },
      { kind: 'pill-room', delay: 300,
        room: ROOMS.vila,
        pill: { text: '📍 8 min a pé', dark: true },
        action: 'Confirmar 1h',
      },
      { kind: 'bot', delay: 600, text: '6 pessoas · livre por 2h · 8,5 créd/h' },
      { kind: 'user', delay: 1800, text: 'Confirmar 1h' },
      { kind: 'bot', typing: 800, text: 'Reservado ✅\nVila Olímpia · 14:32–15:32' },
      { kind: 'quick-replies', delay: 400, items: ['Abrir Maps', 'Avisar o time'] },
    ],
  },

  /* ─────────── P-03 — Recorrência inteligente ─────────── */
  {
    id: 'p03', p: 'P-03',
    title: 'Recorrência inteligente',
    category: 'Padrão de uso',
    summary: 'Detecta padrão após 3 reservas e oferece travar a série toda semana.',
    color: '#a768ff',
    startTime: { h: 17, m: 0 },
    steps: [
      { kind: 'divider', label: 'segunda-feira' },
      { kind: 'bot', typing: 900, text: 'Reparei que você reserva a **sala 02 do Tribbos** toda **terça às 10h**.\n\nQuer que eu já deixe travada toda semana? Você cancela quando quiser.' },
      { kind: 'quick-replies', delay: 600, items: ['Sim, boa ideia', 'Hmm, agora não'] },
      { kind: 'user', delay: 2000, text: 'Sim, boa ideia' },
      { kind: 'open-sheet', delay: 800, sheet: {
        kind: 'recurrence',
        title: 'Repetir esta reserva',
        subtitle: 'Configure as datas recorrentes',
        origin: '27/05 — Terça-feira',
        frequencies: [
          { id: 'weekly',   label: 'Semanalmente',  desc: 'Toda semana, cada terça-feira' },
          { id: 'biweekly', label: 'Quinzenalmente', desc: 'A cada 2 semanas, na terça-feira' },
          { id: 'monthly',  label: 'Mensalmente',    desc: 'Todo mês, na última terça-feira' },
          { id: 'weekdays', label: 'Dias úteis',     desc: 'Todos os dias da semana (seg–sex)' },
        ],
        defaultFreq: 'weekly',
        repeatCount: 3,
        preview: [
          { day: 'TER', dateNum: '27', date: '27/05', month: 'mai. 2026', time: '10:00–12:00', origin: true },
          { day: 'TER', dateNum: '03', date: '03/06', month: 'jun. 2026', time: '10:00–12:00' },
          { day: 'TER', dateNum: '10', date: '10/06', month: 'jun. 2026', time: '10:00–12:00', unavailable: true },
          { day: 'TER', dateNum: '17', date: '17/06', month: 'jun. 2026', time: '10:00–12:00' },
        ],
        cta: 'Confirmar 4 reservas',
      }},
      { kind: 'flow-submitted', delay: 2200, label: 'Reserva recorrente com sucesso' },
      { kind: 'bot', typing: 1000, text: 'Pronto! Sua mesa fixa de terça está garantida pelas próximas **12 semanas** 🎯\n\nToda segunda às 17h te lembro. Se algum dia não rolar, é só me dizer.' },
    ],
  },

  /* ─────────── P-04 — Avisar quem vai com você ─────────── */
  {
    id: 'p04', p: 'P-04',
    title: 'Avise quem vai com você',
    category: 'Pós-reserva',
    summary: 'Após reservar, oferece chamar convidados 1-on-1 com painel de RSVP atualizando.',
    color: '#3a80ce',
    startTime: { h: 10, m: 2 },
    steps: [
      { kind: 'bot', text: 'Reserva confirmada ✅\nTribbos · sala 02 · 10:00' },
      { kind: 'bot', delay: 600, typing: 700, text: 'Quer que eu já avise quem vai com você?' },
      { kind: 'quick-replies', delay: 300, items: ['Sim, avisar', 'Eu mando depois'] },
      { kind: 'user', delay: 1800, text: 'Sim, avisar' },
      { kind: 'open-sheet', delay: 800, sheet: {
        title: 'Quem você vai chamar?',
        subtitle: 'Sugerido pelo evento do Calendar',
        rows: [
          { label: '☑ Joana Maciel', value: 'sugerida' },
          { label: '☑ Pedro Silva',  value: 'sugerido' },
          { label: '☐ Marcelo Reis', value: 'opcional' },
          { label: '+ Adicionar contato', cta: 'Buscar' },
        ],
        cta: 'Enviar pra 3 pessoas',
      }},
      { kind: 'flow-submitted', delay: 2200, label: 'Enviar para 3 pessoas' },
      { kind: 'bot', typing: 900, text: 'Mandei pra 3 pessoas 📨\n\nTe aviso aqui mesmo conforme elas confirmarem.' },
      { kind: 'rsvp-card', delay: 2000,
        items: [
          { name: 'Joana',   s: 'pending' },
          { name: 'Pedro',   s: 'pending' },
          { name: 'Marcelo', s: 'pending' },
        ],
      },
      { kind: 'rsvp-card', delay: 2500,
        items: [
          { name: 'Joana',   s: 'yes' },
          { name: 'Pedro',   s: 'pending' },
          { name: 'Marcelo', s: 'yes' },
        ],
      },
    ],
  },

  /* ─────────── P-05 — Estender reunião ─────────── */
  {
    id: 'p05', p: 'P-05',
    title: 'Estende sua reunião',
    category: 'Durante a reunião',
    summary: 'T-5min do fim — sala segue livre? 3 chips +15/+30/+1h, 1 toque, sem app.',
    color: '#25c265',
    startTime: { h: 10, m: 55 },
    steps: [
      { kind: 'bot', typing: 900, text: 'Sua reunião acaba em **5 min** ⏱️\n\nA sala segue livre por mais 1h. Quer estender?' },
      { kind: 'quick-replies', delay: 300, items: ['+15 min', '+30 min', '+1h', 'Tô finalizando'] },
      { kind: 'user', delay: 1800, text: '+30 min' },
      { kind: 'bot', typing: 800, text: 'Estendido! ✅ Reserva vai até **11:00** agora.\n\nTe aviso de novo perto do fim, ok?' },
    ],
  },

  /* ─────────── P-06 — Falar com a gente ─────────── */
  {
    id: 'p06', p: 'P-06',
    title: 'Falar com a gente (suporte)',
    category: 'Pós-reserva permanente',
    summary: 'Botão fixo no card de confirmação. Triagem por chips, escalation com SLA.',
    color: '#ec4899',
    startTime: { h: 10, m: 18 },
    steps: [
      { kind: 'info-card', title: 'Reserva confirmada ✅',
        lines: ['Tribbos · sala 02', '10:00–11:00'],
        action: '🛠️ Problema com a sala? Fale com a gente',
      },
      { kind: 'user', delay: 1800, text: '[ toca em Fale com a gente ]' },
      { kind: 'bot', typing: 900, text: 'Tô aqui pra ajudar 👋\n\nMe conta rapidinho o que tá rolando?' },
      { kind: 'quick-replies', delay: 300, items: ['Sala suja', 'Equipamento quebrado', 'Não consigo entrar', 'Outro'] },
      { kind: 'user', delay: 1800, text: 'Equipamento quebrado' },
      { kind: 'bot', typing: 700, text: 'Qual equipamento?' },
      { kind: 'quick-replies', delay: 300, items: ['🖥️ TV', '📶 Wi-Fi', '❄️ Ar', '💺 Cadeiras'] },
      { kind: 'user', delay: 1800, text: '🖥️ TV' },
      { kind: 'bot', typing: 900, text: 'Anotado: **TV quebrada**.\n\nTô chamando alguém do Tribbos agora 📞\nTempo médio: **4 min** ⏱️\n\nPrefere resolver por aqui ou recebe ligação?' },
      { kind: 'quick-replies', delay: 300, items: ['Aqui mesmo', 'Pode ligar'] },
    ],
  },

  /* ─────────── P-07 — Sala substituta ─────────── */
  {
    id: 'p07', p: 'P-07',
    title: 'Sala substituta automática',
    category: 'Imprevisto',
    summary: 'Coworking cancela; Sofia já chega com 3 alternativas equivalentes.',
    color: '#de6530',
    startTime: { h: 9, m: 32 },
    steps: [
      { kind: 'bot', typing: 900, text: '⚠️ Olha, o Tribbos avisou agora que sua sala das **10h** não vai dar.\n\nJá procurei e achei **3 alternativas perto** pra você 👇' },
      { kind: 'room', delay: 400, room: ROOMS.vila },
      { kind: 'room', delay: 200, room: ROOMS.itaim },
      { kind: 'room', delay: 200, room: ROOMS.pinheiros },
      { kind: 'bot', delay: 500, text: 'Mantive seu horário (10h–11h) e capacidade (5 pessoas). É só escolher.' },
    ],
  },

  /* ─────────── P-08 — Visita externa ─────────── */
  {
    id: 'p08', p: 'P-08',
    title: 'Pré-cadastro de visitantes',
    category: 'Pré-reunião',
    summary: 'Sofia pergunta se tem visita externa e cuida do cadastro na portaria.',
    color: '#a768ff',
    startTime: { h: 10, m: 3 },
    steps: [
      { kind: 'bot', text: 'Reserva confirmada ✅' },
      { kind: 'bot', delay: 600, typing: 700, text: 'Vai ter **visita de fora** nessa reunião?' },
      { kind: 'quick-replies', delay: 300, items: ['Sim', 'Não', 'Avise depois'] },
      { kind: 'user', delay: 1800, text: 'Sim, 2 visitantes' },
      { kind: 'open-sheet', delay: 800, sheet: {
        title: 'Cadastro de visitantes',
        subtitle: 'Visitante 1 de 2 · Tribbos',
        rows: [
          { label: '👤 Nome', value: 'João Pereira' },
          { label: '📄 Documento', value: '12345678-9' },
          { label: '🏢 Empresa', value: 'opcional' },
          { label: '📷 Foto', cta: '+ Tirar' },
          { label: '+ Próximo visitante', cta: 'Adicionar' },
        ],
        cta: 'Mandar pra recepção',
      }},
      { kind: 'flow-submitted', delay: 2400, label: 'Cadastrar 2 visitantes' },
      { kind: 'bot', typing: 1000, text: 'Tudo certo! ✅\n\nMandei pra recepção do **Tribbos**. **João** e **Marcelo** são esperados — só precisam mostrar documento.' },
    ],
  },

  /* ─────────── P-09 — Review pós-reunião ─────────── */
  {
    id: 'p09', p: 'P-09',
    title: 'Review pós-reunião',
    category: 'Pós-reunião',
    summary: '30 min depois: 🙂/😐/🙁 + categoria. Alimenta ranking de salas.',
    color: '#3a80ce',
    startTime: { h: 11, m: 32 },
    steps: [
      { kind: 'bot', typing: 900, text: 'E aí, como foi sua reunião na **Tribbos sala 02**? 👀' },
      { kind: 'quick-replies', delay: 300, items: ['🙂 Boa', '😐 Ok', '🙁 Ruim'] },
      { kind: 'user', delay: 2000, text: '😐 Ok' },
      { kind: 'bot', typing: 700, text: 'O que poderia ter sido melhor? *(opcional)*' },
      { kind: 'quick-replies', delay: 300, items: ['Limpeza', 'Equipamento', 'Som', 'Temperatura', 'Outro'] },
      { kind: 'user', delay: 1800, text: 'Temperatura' },
      { kind: 'bot', typing: 900, text: 'Ouvido 🙏 Já marquei essa observação na **sala 02** — quem reservar depois vai saber.\n\nSe acontecer de novo, é só me chamar.' },
    ],
  },

  /* ─────────── P-10 — Campanhas temáticas ─────────── */
  {
    id: 'p10', p: 'P-10',
    title: 'Campanhas temáticas',
    category: 'Engajamento',
    summary: 'Sazonalidade vira conversa, não banner. "Segunda fria daquelas ☁️".',
    color: '#f9e10d',
    startTime: { h: 9, m: 5 },
    steps: [
      { kind: 'bot', typing: 900, text: 'Segunda fria daquelas ☁️\n\nAchei 3 salas perto com **café cortesia** essa semana 👇' },
      { kind: 'pill-room', delay: 400,
        room: ROOMS.tribbos,
        pill: { text: '☕ Café cortesia' },
        action: 'Reservar',
      },
      { kind: 'pill-room', delay: 200,
        room: ROOMS.vila,
        pill: { text: '☕ Café cortesia' },
        action: 'Reservar',
      },
      { kind: 'pill-room', delay: 200,
        room: ROOMS.pinheiros,
        pill: { text: '☕ Café cortesia' },
        action: 'Reservar',
      },
      { kind: 'bot', delay: 500, text: 'Se nenhuma servir, é só me chamar 💛' },
    ],
  },

  /* ─────────── P-11 — Boas-vindas / Onboarding ─────────── */
  {
    id: 'p11', p: 'P-11',
    title: 'Boas-vindas',
    category: 'Onboarding',
    summary: '1ª mensagem após cadastro. 3 bullets do que faz + convite pra reservar.',
    color: '#f9e10d',
    startTime: { h: 10, m: 14 },
    steps: [
      { kind: 'divider', label: 'Hoje' },
      { kind: 'bot', typing: 900, text: 'Oi, **Marina**! 👋 Bem-vinda à Woba.\n\nEu sou a **Sofia**, sua assistente. Aqui pelo WhatsApp eu cuido de:\n\n🪑 **Achar e reservar salas** em qualquer coworking parceiro\n📅 **Lembrar você** antes e depois da reunião\n🛠️ **Resolver problemas** se algo não rolar na sala' },
      { kind: 'quick-replies', delay: 600, items: ['Reservar uma sala', 'Como funciona?', 'Depois eu vejo'] },
    ],
  },

  /* ─────────── P-12 — Re-engagement D+7 ─────────── */
  {
    id: 'p12', p: 'P-12',
    title: 'Re-engagement personalizado',
    category: 'Re-engajamento',
    summary: '7 dias sem reservar — sugestão baseada no histórico, com saída de respeito.',
    color: '#fe8c14',
    startTime: { h: 9, m: 12 },
    steps: [
      { kind: 'divider', label: 'terça-feira' },
      { kind: 'bot', typing: 900, text: 'Oi! Essa semana você ainda não reservou nada por aqui 👀\n\nReparei que você costuma reservar **Tribbos quartas de manhã**. A **sala 02** tá livre essa quarta no mesmo horário 👇' },
      { kind: 'pill-room', delay: 400,
        room: ROOMS.tribbos,
        pill: { text: '✨ Sua escolha frequente' },
        action: '📋 Reservar essa',
      },
      { kind: 'quick-replies', delay: 400, items: ['Outro horário', 'Outra sala', 'Tô fora essa semana'] },
    ],
  },

  /* ─────────── P-13 — Reservar de novo ─────────── */
  {
    id: 'p13', p: 'P-13',
    title: 'Reservar de novo',
    category: 'Atalho',
    summary: 'Saudação oferece as 3 últimas reservas como atalho — Flow já preenchido.',
    color: '#a768ff',
    startTime: { h: 14, m: 8 },
    steps: [
      { kind: 'user', text: 'oi' },
      { kind: 'bot', typing: 800, text: 'Oi, **Marina**! 👋\n\nQuer repetir alguma das suas últimas reservas? 👇' },
      { kind: 'pill-room', delay: 400,
        room: ROOMS.tribbos,
        pill: { text: '🕒 há 3 dias', dark: true },
        action: '🔄 Reservar de novo',
      },
      { kind: 'pill-room', delay: 200,
        room: ROOMS.vila,
        pill: { text: '🕒 semana passada', dark: true },
        action: '🔄 Reservar de novo',
      },
      { kind: 'pill-room', delay: 200,
        room: ROOMS.itaim,
        pill: { text: '🕒 há 2 semanas', dark: true },
        action: '🔄 Reservar de novo',
      },
      { kind: 'quick-replies', delay: 400, items: ['Buscar nova', 'Outro horário'] },
    ],
  },

  /* ─────────── P-14 — Chamado técnico (privativo) ─────────── */
  {
    id: 'p14', p: 'P-14',
    title: 'Chamado técnico — privativo',
    category: 'Operação',
    summary: 'Linguagem natural → Flow estruturado → ticket com SLA + updates async.',
    color: '#de6530',
    startTime: { h: 15, m: 42 },
    steps: [
      { kind: 'user', text: 'ar condicionado parou de novo' },
      { kind: 'bot', typing: 900, text: 'Vou abrir um chamado pro **Tribbos** agora.\n\nMe ajuda com 3 coisas rapidinhas?' },
      { kind: 'open-sheet', delay: 800, sheet: {
        title: 'Abrir chamado',
        intro: 'Tribbos · Escritório privativo',
        rows: [
          { label: '🔥 Severidade', value: 'Alto ●', accent: 'var(--chat-link)', bold: true },
          { label: '📍 Local', value: 'Sala 2' },
          { label: '📷 Foto', cta: '+ Anexar' },
          { label: '📝 Descrição', value: 'opcional' },
        ],
        cta: 'Abrir chamado',
      }},
      { kind: 'flow-submitted', delay: 2600, label: 'Abrir chamado · TV quebrada' },
      { kind: 'ticket-card', delay: 600, id: '#2143', severity: 'Alto', eta: '2h', status: 'aberto' },
      { kind: 'bot', typing: 1200, delay: 1800, text: 'Atualização do **#2143**:\n\n👷 **Marcelo** do time do Tribbos confirmou. Ele tá indo aí agora.\n⏱️ Chegada estimada: 15 min' },
    ],
  },

  /* ─────────── P-15 — FAQ / dúvidas operacionais (Nível 1) ─────────── */
  {
    id: 'p15', p: 'P-15',
    title: 'FAQ — autoatendimento Nível 1',
    category: 'Suporte',
    summary: 'Base de conhecimento conversacional. "Como funciona", "qual prazo", "onde acho".',
    color: '#3a80ce',
    startTime: { h: 13, m: 22 },
    steps: [
      { kind: 'user', text: 'como funciona os créditos?' },
      { kind: 'bot', typing: 1000, text: 'Boa pergunta! 💛\n\n**Créditos Woba** funcionam assim:\n\n💳 Cada plano libera créditos por mês\n⏱️ Você usa em qualquer coworking parceiro\n🔄 Sobrou? Acumula até o mês seguinte (limite de 50%)\n📅 Reservas canceladas até 2h antes devolvem o crédito\n\nQuer ver seu saldo atual?' },
      { kind: 'info-card', delay: 400,
        title: '↗ Ver detalhes no app',
        lines: ['`woba://carteira/creditos`', 'Saldo, extrato e plano'],
        accent: 'var(--chat-link)',
      },
      { kind: 'quick-replies', delay: 400, items: ['Resolvi 👍', 'Falar com humano', 'Outra dúvida'] },
      { kind: 'user', delay: 2200, text: 'Resolvi 👍' },
      { kind: 'bot', typing: 700, text: 'Show! Se aparecer outra dúvida, é só me chamar 💛\n\n📚 Você pode ler mais em: dúvidas frequentes' },
    ],
  },

  /* ─────────── P-16 — Consultar minha reserva ─────────── */
  {
    id: 'p16', p: 'P-16',
    title: 'Onde é minha próxima reunião?',
    category: 'Self-service',
    summary: 'Lê dados da reserva e responde em linguagem natural — endereço, horário, capacidade.',
    color: '#81c42b',
    startTime: { h: 8, m: 14 },
    steps: [
      { kind: 'user', text: 'onde é minha próxima reunião?' },
      { kind: 'bot', typing: 900, text: 'Sua próxima reunião é hoje às **10h** na **Tribbos Coworking** 👇' },
      { kind: 'location-card', delay: 400,
        title: 'Tribbos Coworking',
        address: 'Av. Marechal Floriano Peixoto, 720 — Centro',
        mapImage: 'assets/map-1.svg',
      },
      { kind: 'bot', delay: 500, text: 'Sala 02 · 2º andar · capacidade pra 5 pessoas.' },
      { kind: 'quick-replies', delay: 400, items: ['Como chegar', 'Capacidade', 'Convidados', 'Trocar local'] },
      { kind: 'user', delay: 2000, text: 'Convidados' },
      { kind: 'bot', typing: 800, text: 'Você convidou 3 pessoas:' },
      { kind: 'rsvp-card', delay: 400,
        items: [
          { name: 'Joana Maciel', s: 'yes' },
          { name: 'Pedro Silva',  s: 'pending' },
          { name: 'Marcelo Reis', s: 'yes' },
        ],
      },
    ],
  },

  /* ─────────── P-17 — Cancelar reserva ─────────── */
  {
    id: 'p17', p: 'P-17',
    title: 'Cancelar reserva',
    category: 'Self-service',
    summary: 'Identifica a reserva, pergunta motivo opcional, devolve créditos visivelmente.',
    color: '#de6530',
    startTime: { h: 16, m: 4 },
    steps: [
      { kind: 'user', text: 'preciso cancelar a reserva de amanhã' },
      { kind: 'bot', typing: 900, text: 'Achei aqui 👇' },
      { kind: 'info-card', delay: 400,
        title: 'Tribbos · sala 02',
        lines: ['Amanhã · 10:00–12:00', '5 pessoas · 14 créditos'],
      },
      { kind: 'bot', delay: 500, text: 'Cancelando agora você **recebe os 14 créditos de volta** (ainda tá no prazo).\n\nQuer continuar?' },
      { kind: 'quick-replies', delay: 400, items: ['Sim, cancelar', 'Não, vou manter'] },
      { kind: 'user', delay: 2000, text: 'Sim, cancelar' },
      { kind: 'open-sheet', delay: 600, sheet: {
        title: 'Cancelar reserva',
        intro: 'Tribbos · sala 02',
        subtitle: 'Amanhã · 10:00–12:00',
        rows: [
          { label: '💳 Créditos a devolver', value: '14 créd', accent: 'var(--chat-link)', bold: true },
          { label: '📝 Motivo', value: 'opcional' },
          { label: '🔔 Avisar convidados?', value: 'Sim ●', accent: 'var(--chat-link)' },
        ],
        cta: 'Cancelar reserva',
      }},
      { kind: 'flow-submitted', delay: 2400, label: 'Cancelar reserva' },
      { kind: 'bot', typing: 900, text: 'Reserva cancelada ✅\n\n💳 **14 créditos** voltaram pra sua carteira\n📨 Joana, Pedro e Marcelo foram avisados\n\nSe precisar marcar outra, é só falar comigo 💛' },
    ],
  },

  /* ─────────── P-18 — Remarcar reserva ─────────── */
  {
    id: 'p18', p: 'P-18',
    title: 'Remarcar reserva',
    category: 'Self-service',
    summary: 'Mantém a mesma sala, desliza pra outra data. Avisa os convidados automaticamente.',
    color: '#a768ff',
    startTime: { h: 9, m: 32 },
    steps: [
      { kind: 'user', text: 'quero mudar a reunião de amanhã pra quinta' },
      { kind: 'bot', typing: 900, text: 'Entendi! Sua reunião era:\n\n**Tribbos · sala 02**\n📅 Amanhã (quarta) · 10:00–12:00\n\nQuer manter o mesmo horário (10h–12h) na **quinta**?' },
      { kind: 'quick-replies', delay: 400, items: ['Sim, quinta 10h', 'Outro horário', 'Cancela então'] },
      { kind: 'user', delay: 2000, text: 'Sim, quinta 10h' },
      { kind: 'bot', typing: 800, text: 'Vou checar se a sala 02 tá livre na quinta…' },
      { kind: 'bot', typing: 1100, delay: 1500, text: 'Boa notícia: **livre** 🎯\n\nConfirmo a troca pra quinta 10h-12h?' },
      { kind: 'open-sheet', delay: 700, sheet: {
        title: 'Remarcar reserva',
        intro: 'Tribbos · sala 02',
        subtitle: 'De quarta → quinta · 10:00–12:00',
        rows: [
          { label: '📅 Nova data', value: 'Quinta · 23/05', accent: 'var(--chat-link)', bold: true },
          { label: '⏰ Horário', value: '10:00–12:00' },
          { label: '💳 Créditos', value: 'mantidos · 14' },
          { label: '🔔 Avisar convidados?', value: 'Sim ●', accent: 'var(--chat-link)' },
        ],
        cta: 'Confirmar remarcação',
      }},
      { kind: 'flow-submitted', delay: 2600, label: 'Confirmar remarcação' },
      { kind: 'bot', typing: 900, text: 'Pronto! ✅\n\n📅 Agora é **quinta às 10h** na **Tribbos sala 02**\n📨 Já avisei Joana, Pedro e Marcelo com o novo horário\n\nTe lembro na quarta à noite 👋' },
    ],
  },

  /* ─────────── P-19 — Trocar local da reserva ─────────── */
  {
    id: 'p19', p: 'P-19',
    title: 'Trocar de local',
    category: 'Self-service',
    summary: 'Mesma data e horário, outra sala. 3 alternativas equivalentes — visual rich.',
    color: '#fe8c14',
    startTime: { h: 14, m: 50 },
    steps: [
      { kind: 'user', text: 'essa sala da Tribbos não tá legal, dá pra trocar pra outra perto?' },
      { kind: 'bot', typing: 1000, text: 'Claro! Vou manter seu **horário (10h–12h)** e **5 pessoas**, e te mostro 3 alternativas perto 👇' },
      { kind: 'pill-room', delay: 400,
        room: ROOMS.vila,
        pill: { text: '✨ Mais bem avaliada' },
        action: '🔄 Trocar pra essa',
      },
      { kind: 'pill-room', delay: 200,
        room: ROOMS.itaim,
        pill: { text: '📍 Mais perto', dark: true },
        action: '🔄 Trocar pra essa',
      },
      { kind: 'pill-room', delay: 200,
        room: ROOMS.pinheiros,
        pill: { text: '💳 Mesmo crédito', dark: true },
        action: '🔄 Trocar pra essa',
      },
      { kind: 'bot', delay: 500, text: 'Quando você escolher, eu cancelo a anterior e mando o novo endereço pros convidados.' },
    ],
  },

  /* ─────────── N-06A — CSAT do agente (positivo) ─────────── */
  {
    id: 'n06a', p: 'N-06A',
    title: 'CSAT — conversa resolvida',
    category: 'Pós-atendimento',
    summary: 'Após resolver qualquer assunto, Sofia pergunta se conseguiu ajudar. Caminho positivo com encerramento limpo.',
    color: '#25c265',
    startTime: { h: 11, m: 14 },
    steps: [
      { kind: 'bot', text: 'Reserva confirmada ✅\n**Tribbos** · sala 02 · amanhã 10h–12h' },
      { kind: 'bot', delay: 900, typing: 600, text: 'Consegui te ajudar com isso? 😊' },
      { kind: 'quick-replies', delay: 300, items: ['Sim, resolveu 👍', 'Não totalmente'] },
      { kind: 'user', delay: 2000, text: 'Sim, resolveu 👍' },
      { kind: 'bot', typing: 600, text: 'Que ótimo! 💛 Qualquer outra coisa, é só me chamar.' },
    ],
  },

  /* ─────────── N-06B — CSAT do agente (negativo) ─────────── */
  {
    id: 'n06b', p: 'N-06B',
    title: 'CSAT — não resolvido',
    category: 'Pós-atendimento',
    summary: 'CSAT negativo com chips de motivo. Usuário sinaliza o que faltou — alimenta melhoria contínua do agente.',
    color: '#de6530',
    startTime: { h: 15, m: 40 },
    steps: [
      { kind: 'bot', text: 'Encaminhei sua dúvida pro time de suporte 📨\nEles te retornam em até **8 min**.' },
      { kind: 'bot', delay: 900, typing: 600, text: 'Consegui te ajudar com isso? 😊' },
      { kind: 'quick-replies', delay: 300, items: ['Sim, resolveu 👍', 'Não totalmente'] },
      { kind: 'user', delay: 2000, text: 'Não totalmente' },
      { kind: 'bot', typing: 700, text: 'Que pena 😕\n\nO que eu poderia ter feito melhor? *(opcional)*' },
      { kind: 'quick-replies', delay: 300, items: ['Resposta incompleta', 'Demorou demais', 'Não entendeu o problema', 'Outro motivo'] },
      { kind: 'user', delay: 2000, text: 'Resposta incompleta' },
      { kind: 'bot', typing: 900, text: 'Obrigada pelo feedback 🙏 Vou usar isso pra melhorar.\n\nSe ainda precisar, pode me chamar ou falar direto com o suporte.' },
    ],
  },

  /* ─────────── H-01 — Histórico · última reserva ─────────── */
  {
    id: 'h01', p: 'H-01',
    title: 'Última reserva',
    category: 'Histórico & Preferências',
    summary: 'Usuário pergunta sobre a última reserva — Sofia responde com card e oferece reservar de novo.',
    color: '#3a80ce',
    startTime: { h: 9, m: 8 },
    steps: [
      { kind: 'user', text: 'qual foi minha última reserva?' },
      { kind: 'bot', typing: 900, text: 'Achei aqui 👇' },
      { kind: 'info-card', delay: 400,
        title: 'Tribbos Coworking · sala 02',
        lines: ['📅 14/05 · semana passada · 10:00–12:00', '👥 5 pessoas · 14 créditos', '✅ Check-in realizado'],
      },
      { kind: 'bot', delay: 500, text: 'Quer reservar o mesmo espaço de novo?' },
      { kind: 'quick-replies', delay: 300, items: ['Reservar de novo', 'Ver histórico completo', 'Não, obrigado'] },
      { kind: 'user', delay: 2000, text: 'Reservar de novo' },
      { kind: 'bot', typing: 800, text: 'Boa! Para quando? Posso manter o mesmo horário (**10h–12h**)?' },
      { kind: 'quick-replies', delay: 300, items: ['Amanhã 10h', 'Essa semana', 'Outra data'] },
    ],
  },

  /* ─────────── H-02 — Histórico · espaços favoritos ─────────── */
  {
    id: 'h02', p: 'H-02',
    title: 'Espaços favoritos',
    category: 'Histórico & Preferências',
    summary: 'Sofia analisa o padrão das últimas reservas e revela o top 3 de coworkings e a janela horária preferida.',
    color: '#a768ff',
    startTime: { h: 13, m: 22 },
    steps: [
      { kind: 'user', text: 'onde eu mais costumo reservar?' },
      { kind: 'bot', typing: 1100, text: 'Analisei suas últimas **12 reservas**. Veja seu padrão 👇' },
      { kind: 'info-card', delay: 400,
        title: '📊 Seus espaços mais frequentes',
        lines: [
          '🥇 Tribbos Coworking — 5 reservas',
          '🥈 Vila Olímpia Hub — 4 reservas',
          '🥉 WorkBricks Itaim — 3 reservas',
        ],
      },
      { kind: 'bot', delay: 500, text: '**Terças de manhã** são sua janela mais frequente ⏰\n\nQuer reservar em algum deles agora?' },
      { kind: 'quick-replies', delay: 300, items: ['Tribbos', 'Vila Olímpia', 'Itaim', 'Buscar outro'] },
    ],
  },

  /* ─────────── H-03 — Histórico · consumo de créditos ─────────── */
  {
    id: 'h03', p: 'H-03',
    title: 'Consumo de créditos',
    category: 'Histórico & Preferências',
    summary: 'Sofia puxa o extrato do mês atual e projeta quantas reservas ainda cabem no saldo restante.',
    color: '#fe8c14',
    startTime: { h: 16, m: 44 },
    steps: [
      { kind: 'user', text: 'quanto crédito eu usei esse mês?' },
      { kind: 'bot', typing: 1000, text: 'Puxando seu extrato de maio 2026…' },
      { kind: 'info-card', delay: 700,
        title: '💳 Extrato · maio 2026',
        lines: [
          'Reservas realizadas: 6',
          'Créditos usados: 48 de 80',
          'Créditos restantes: 32',
          'Maior uso: Tribbos (21 créd.)',
          'Renovação: 01/06/2026',
        ],
      },
      { kind: 'bot', delay: 400, text: 'Você ainda tem **32 créditos** — dá pra mais 4 reservas no seu padrão de uso.\n\nO plano renova em **01/06**.' },
      { kind: 'quick-replies', delay: 300, items: ['Ver extrato no app', 'Reservar agora', 'Entendido 👍'] },
    ],
  },

  /* ─────────── H-04 — Histórico · salvar preferência ─────────── */
  {
    id: 'h04', p: 'H-04',
    title: 'Salvar preferência',
    category: 'Histórico & Preferências',
    summary: 'Usuário define região e capacidade padrão para buscas futuras. Sofia confirma, salva e aplica na próxima busca.',
    color: '#81c42b',
    startTime: { h: 10, m: 5 },
    steps: [
      { kind: 'user', text: 'quero que você me sugira sempre salas em Pinheiros pra até 5 pessoas' },
      { kind: 'bot', typing: 1000, text: 'Anotado! ✍️ Vou guardar como sua preferência padrão:' },
      { kind: 'info-card', delay: 400,
        title: '⭐ Preferência salva',
        lines: [
          '📍 Região: Pinheiros, São Paulo',
          '👥 Capacidade: até 5 pessoas',
        ],
      },
      { kind: 'bot', delay: 500, text: 'Da próxima vez que você pedir uma sala sem especificar o local, começo por **Pinheiros**.\n\nQuer adicionar mais alguma preferência?' },
      { kind: 'quick-replies', delay: 300, items: ['Adicionar horário fixo', 'Mudar região', 'Tá ótimo, obrigado!'] },
      { kind: 'user', delay: 2000, text: 'Tá ótimo, obrigado!' },
      { kind: 'bot', typing: 600, text: 'Show! 💛 Preferências salvas. Próxima busca já vai ser mais rápida.' },
    ],
  },

  /* ─────────── I-04 — Reservar por voz ─────────── */
  {
    id: 'i04', p: 'I-04',
    title: 'Reservar por voz',
    category: 'Ideação · em proto',
    summary: 'Aperta o microfone, fala "sala pra 4 em Pinheiros amanhã 14h" — Sofia entende.',
    color: '#a768ff',
    startTime: { h: 18, m: 32 },
    steps: [
      { kind: 'voice-message', side: 'user', duration: '0:09' },
      { kind: 'bot', typing: 1200, text: '🎙️ Transcrevendo…' },
      { kind: 'info-card', delay: 1000,
        title: '🎙️ Você falou:',
        lines: ['"preciso de uma sala pra 4 pessoas em Pinheiros amanhã das 14 às 17h"'],
        accent: 'var(--chat-text-2)',
      },
      { kind: 'bot', typing: 1100, delay: 800, text: 'Entendi assim 👇' },
      { kind: 'info-card', delay: 400,
        title: 'Critérios captados',
        lines: [
          '📍 Pinheiros',
          '👥 4 pessoas',
          '📅 Amanhã (quarta · 23/05)',
          '⏰ 14:00 – 17:00',
        ],
      },
      { kind: 'bot', delay: 500, text: 'Tá certo? Posso buscar?' },
      { kind: 'quick-replies', delay: 400, items: ['Tá certo, buscar', 'Mudar algo', 'Cancelar'] },
      { kind: 'user', delay: 2200, text: 'Tá certo, buscar' },
      { kind: 'bot', typing: 1300, text: 'Achei 2 opções em Pinheiros que servem 🎯' },
      { kind: 'room', delay: 400, room: ROOMS.pinheiros },
      { kind: 'room', delay: 200, room: ROOMS.vila },
    ],
  },

  /* ─────────── W-02 — Mesa solo · crossell na confirmação ─────────── */
  {
    id: 'w02', p: 'W-02',
    title: 'Mesa solo · crossell',
    category: 'Ideação · em proto',
    summary: 'Ao confirmar sala, check para adicionar mesa individual por +1,25 créd. Total sobe de 21 para 22,25.',
    color: '#cadb66',
    startTime: { h: 11, m: 5 },
    steps: [
      { kind: 'user', text: 'quero reservar uma sala pra amanhã 14h no Tribbos' },
      { kind: 'bot', typing: 1100, text: 'Pode ser! Vou abrir a confirmação aqui 👇' },
      { kind: 'open-sheet', delay: 800, sheet: {
        title: 'Confirmar reserva',
        intro: 'Tribbos Coworking',
        subtitle: 'Sala de reunião 02 · 23/05 · 14:00–17:00',
        rows: [
          { label: '👥 Pessoas', value: '3 pessoas' },
          { label: '⏱️ Duração', value: '3h' },
          { label: '📍 Endereço', value: 'Av. M. Floriano P., 720' },
          { label: '💳 Total', value: '21 créditos', isTotal: true, bold: true },
        ],
        offer: {
          checkbox: true,
          emoji: '🪑',
          label: 'Add-on · crossell',
          title: 'Adicionar mesa individual',
          subtitle: 'Chegue mais cedo ou fique depois — mesa na área comum com café e Wi-Fi.',
          extraLabel: '+1,25 créd',
          totalWithOffer: '22,25 créditos',
        },
        cta: 'Solicitar reserva',
      }},
      { kind: 'flow-submitted', delay: 5000, label: 'Solicitar reserva' },
      { kind: 'bot', typing: 1100, text: 'Tudo certo! Reserva confirmada ✅\n\n🏢 **Tribbos** · sala 02 · amanhã 14h–17h\n🪑 Mesa individual inclusa\n\n💳 **22,25 créditos** debitados\n☕ Café na mesa te espera!' },
    ],
  },
];

window.SCENARIOS = SCENARIOS;

})();
