// scenarios.jsx — Data for all scenario scripts (S-01..S-03 setup, P-01..P-20, H-01..H-04).
// Each scenario has: id, p (P-NN), title, category, summary, color, steps[].
// Step kinds: bot · user · divider · room · pill-room · carousel · quick-replies ·
//             info-card · gift-card · app-screen · ticket-card · rsvp-card ·
//             open-sheet · close-sheet · flow-submitted · wait

(function () {

const ROOMS = {
  tribbos: {
    id: 'r-tribbos', coworking: 'Tribbos Coworking',
    name: 'sala de reunião 02', capacity: 5, credits: 7,
    image: 'assets/room-1.svg',
    date: '16/05/2026', inicio: '10:00', fim: '17:00',
    address: 'Av. Marechal Floriano Peixoto, 720 — Casarão Histórico, Centro',
    amenities: 'Wi-Fi, Café, Ar condicionado',
  },
  vila: {
    id: 'r-vila', coworking: 'Vila Olímpia Hub',
    name: 'sala criativa 04', capacity: 6, credits: 8.5,
    image: 'assets/room-2.svg',
    date: '16/05/2026', inicio: '09:00', fim: '13:00',
    address: 'R. Funchal, 418 — Vila Olímpia, São Paulo',
    amenities: 'Wi-Fi, Café, Projetor, Lousa',
  },
  itaim: {
    id: 'r-itaim', coworking: 'WorkBricks Itaim',
    name: 'sala executiva', capacity: 8, credits: 9,
    image: 'assets/room-3.svg',
    date: '16/05/2026', inicio: '14:00', fim: '18:00',
    address: 'R. Leopoldo Couto de Magalhães Jr., 700 — Itaim Bibi',
    amenities: 'Wi-Fi, Café, TV 65", Videoconferência',
  },
  pinheiros: {
    id: 'r-pinh', coworking: 'Hub Pinheiros',
    name: 'sala 01', capacity: 5, credits: 7.5,
    image: 'assets/room-1.svg',
    date: '16/05/2026', inicio: '11:00', fim: '15:00',
    address: 'R. dos Pinheiros, 498 — Pinheiros, São Paulo',
    amenities: 'Wi-Fi, Café, Ar condicionado',
  },

  // Setup com a Sofia (S-01..S-03)
  wsPinheiros: {
    id: 'ws-pinh', coworking: 'Hub Pinheiros',
    name: 'mesa compartilhada', capacity: 1, credits: 1.5,
    image: 'assets/room-1.svg',
    date: '01/10/2026', inicio: '09:00', fim: '18:00',
    address: 'R. dos Pinheiros, 498 — Pinheiros, São Paulo',
    amenities: 'Wi-Fi, Café, Cabine de call',
  },
  wsFradique: {
    id: 'ws-frad', coworking: 'Fradique Work',
    name: 'mesa compartilhada', capacity: 1, credits: 1.5,
    image: 'assets/room-2.svg',
    date: '01/10/2026', inicio: '08:00', fim: '20:00',
    address: 'R. Fradique Coutinho, 1117 — Pinheiros, São Paulo',
    amenities: 'Wi-Fi, Café, Ar condicionado',
  },
  wsVilaMadalena: {
    id: 'ws-vmad', coworking: 'Madalena Coletivo',
    name: 'mesa compartilhada', capacity: 1, credits: 2,
    image: 'assets/room-3.svg',
    date: '01/10/2026', inicio: '09:00', fim: '19:00',
    address: 'R. Harmonia, 250 — Vila Madalena, São Paulo',
    amenities: 'Wi-Fi, Café, Terraço',
  },
  wsMoema: {
    id: 'ws-moema', coworking: 'Moema Work',
    name: 'mesa compartilhada', capacity: 1, credits: 1.5,
    image: 'assets/room-2.svg',
    date: '13/10/2026', inicio: '09:30', fim: '18:00',
    address: 'Av. Ibirapuera, 2120 — Moema, São Paulo',
    amenities: 'Wi-Fi, Café, Cabine de call',
  },
  mrFariaLima: {
    id: 'mr-flima', coworking: 'Faria Lima Offices',
    name: 'sala de reunião 3', capacity: 8, credits: 9.5,
    image: 'assets/room-1.svg',
    date: '07/10/2026', inicio: '09:00', fim: '12:00',
    address: 'Av. Brig. Faria Lima, 3900 — Itaim Bibi',
    amenities: 'Wi-Fi, Café, Tela 75", Estacionamento',
  },
  mrJK: {
    id: 'mr-jk', coworking: 'JK Business Hub',
    name: 'sala board', capacity: 10, credits: 11,
    image: 'assets/room-2.svg',
    date: '07/10/2026', inicio: '09:00', fim: '12:00',
    address: 'Av. Pres. Juscelino Kubitschek, 1400 — Itaim Bibi',
    amenities: 'Wi-Fi, Café, Projetor, Estacionamento',
  },
};

const SCENARIOS = [
  /* ─────────── S-01 — Setup Individual: Sofia se apresenta e calibra ─────────── */
  {
    id: 's01', p: 'S-01',
    title: 'Setup com a Sofia — pra mim',
    category: 'Setup com a Sofia',
    summary: 'Logo após o cadastro, a Sofia oferta o que faz e coleta 3 preferências (onde, dias, tipo). Cada resposta já devolve espaços — e termina na 1ª reserva.',
    color: '#f9e10d',
    startTime: { h: 9, m: 12 },
    spec: {
      purpose: 'Substituir o setup de hoje (matrícula no plano da empresa, que prevê reservar só 1,09×) por um setup de produto: a Sofia se apresenta, oferta as capacidades e calibra o perfil do colaborador em 3 perguntas. É a hipótese H1 do Playbook Reforge (aba 6) e a oportunidade O1 — "tenho o benefício, mas esqueço que ele existe".',
      whenToUse: 'Primeiro contato após o cadastro (ou 1º login) de um colaborador sem nenhuma reserva. No WhatsApp, só com opt-in do número no cadastro; no app, no lugar do onboarding de 3 telas (36% recusam a tela de boas-vindas).',
      trigger: 'Evento de conta criada + opt-in de canal. A Sofia inicia; o usuário pode responder "agora não" e o setup fica para o momento de dor (ver S-03).',
      flow: 'Pedido → valor → pedido: (1) apresentação + 4 capacidades; (2) pra quem reserva (Individual × Organizador); (3) referência de local → devolve 3 espaços que confirmam na hora; (4) dias fora de casa (multi-seleção); (5) tipo de espaço; (6) resumo do perfil editável; (7) oferta da 1ª reserva no próximo dia preferido; (8) permissão para avisar na véspera.',
      inputs: 'Reusa o contrato que o app já tem, sem criar outro modelo: atributos em /users/{id}/attributes (onboarding_product, onboarding_frequency_day, onboarding_amenities, onboarding_welcome) + endereço em /address (tipo "other", com lat/long). Novos atributos: sofia_persona, sofia_notify_eve. A Sofia passa a ler esse perfil em toda conversa (hoje não lê nada e não tem memória entre sessões).',
      outcome: 'Perfil calibrado em menos de 1 minuto, 1ª reserva confirmada no canal e gatilho de véspera autorizado — o loop manufaturado "repetir o lugar" já nasce armado.',
      success: 'Métrica principal: % da coorte com 1ª reserva em 30 dias do cadastro (hoje 6,3%; alvo do teste +5 a +10 p.p.). Secundárias: setup concluído entre expostos, tempo até a 1ª reserva (mediana hoje 73 dias no Individual). Trade-off: opt-out do canal no 1º contato.',
    },
    steps: [
      { kind: 'divider', label: 'segunda-feira, 28/09' },
      { kind: 'bot', typing: 900, text: 'Oi, Marina! Eu sou a **Sofia**, da Woba 👋\n\nSua empresa liberou espaços de trabalho pra você, sem custo nenhum.' },
      { kind: 'info-card', delay: 500,
        title: 'O que eu faço por você',
        lines: [
          '🔎 **Encontro** um lugar perto de você que confirma na hora',
          '📅 **Reservo** mesa, sala ou evento aqui mesmo',
          '🔁 **Repito** o lugar que funcionou, em 1 toque',
          '🆘 **Acho** outro lugar quando algo dá errado',
        ],
      },
      { kind: 'bot', typing: 800, delay: 400, text: 'Pra acertar de primeira, preciso te conhecer em 3 perguntas. Leva menos de 1 minuto.' },
      { kind: 'quick-replies', delay: 300, items: ['Vamos lá', 'Agora não'] },
      { kind: 'user', delay: 1600, text: 'Vamos lá' },
      { kind: 'bot', typing: 700, text: 'Você vai reservar mais pra você ou pro seu time?' },
      { kind: 'quick-replies', delay: 300, items: ['Pra mim', 'Pro meu time', 'Os dois'] },
      { kind: 'user', delay: 1600, text: 'Pra mim' },
      { kind: 'bot', typing: 800, text: 'Anotado! Onde você costuma estar nos dias fora de casa?\n\nEnvie o bairro ou a sua localização 📍' },
      { kind: 'user', delay: 1800, text: 'Pinheiros, perto do metrô Fradique' },
      { kind: 'bot', typing: 600, text: 'Deixa eu checar o que tem por aí.' },
      { kind: 'bot', typing: 1400, text: 'Achei 3 espaços a até 10 min de você, todos com **confirmação na hora** 👇' },
      { kind: 'carousel', delay: 300, rooms: [ROOMS.wsPinheiros, ROOMS.wsFradique, ROOMS.wsVilaMadalena] },
      { kind: 'bot', typing: 800, delay: 800, text: 'Sem pressa pra escolher. Quais dias você costuma sair de casa?' },
      { kind: 'open-sheet', delay: 600, sheet: {
        title: 'Seus dias fora de casa',
        intro: 'Quais dias você trabalha fora?',
        subtitle: 'Marque quantos quiser. Dá pra mudar depois.',
        rows: [
          { label: '☐ Segunda' },
          { label: '☑ Terça', value: 'selecionado', accent: 'var(--chat-link)' },
          { label: '☐ Quarta' },
          { label: '☑ Quinta', value: 'selecionado', accent: 'var(--chat-link)' },
          { label: '☐ Sexta' },
          { label: '☐ Varia toda semana' },
        ],
        cta: 'Salvar dias',
      }},
      { kind: 'flow-submitted', delay: 2200, label: 'Terça e quinta' },
      { kind: 'bot', typing: 700, text: 'Terça e quinta, combinado. O que você mais precisa nesses dias?' },
      { kind: 'quick-replies', delay: 300, items: ['Mesa pra focar', 'Sala pra call', 'Os dois'] },
      { kind: 'user', delay: 1600, text: 'Mesa pra focar' },
      { kind: 'info-card', delay: 600,
        title: '✓ Seu perfil com a Sofia',
        lines: [
          '👤 Reserva pra você',
          '📍 Pinheiros · até 10 min',
          '📅 Terças e quintas',
          '🪑 Mesa pra focar',
        ],
        action: 'Editar preferências',
        accent: 'var(--chat-link)',
      },
      { kind: 'bot', typing: 900, delay: 400, text: 'Com isso eu já sei o que te mostrar primeiro.\n\nQuer garantir sua mesa nesta **quinta, 01/10**?' },
      { kind: 'pill-room', delay: 300,
        room: ROOMS.wsPinheiros,
        pill: { text: '📍 6 min a pé · confirma na hora', dark: true },
        action: 'Reservar quinta',
      },
      { kind: 'user', delay: 1800, text: 'Reservar quinta' },
      { kind: 'bot', typing: 900, text: 'Sua reserva está confirmada ✅\n\n**Hub Pinheiros** · mesa compartilhada\nquinta, 01/10 · 9h–18h\n💳 1,5 crédito da sua empresa · cancele até 48h antes' },
      { kind: 'bot', typing: 800, delay: 600, text: 'Última coisa: posso te avisar na véspera dos seus dias quando tiver lugar bom livre?' },
      { kind: 'quick-replies', delay: 300, items: ['Pode avisar', 'Só quando eu pedir'] },
      { kind: 'user', delay: 1600, text: 'Pode avisar' },
      { kind: 'bot', typing: 800, text: 'Combinado! Aviso toda segunda e quarta à noite.\n\nSe a rotina mudar, é só me dizer "mudei de rotina".' },
    ],
  },

  /* ─────────── S-02 — Setup Organizador: time, cadência e o que não pode faltar ─────────── */
  {
    id: 's02', p: 'S-02',
    title: 'Setup com a Sofia — pro meu time',
    category: 'Setup com a Sofia',
    summary: 'Para quem organiza encontros: a Sofia coleta tamanho do time, cadência, o que não pode faltar e o local. Já sugere a recorrência na 1ª sala e entrega o convite pronto.',
    color: '#f9e10d',
    startTime: { h: 10, m: 4 },
    spec: {
      purpose: 'Calibrar a Sofia para o Organizador (35% da base, 88% do crédito) e sugerir a cadência já na 1ª sala — hipótese H3 (aba 6) e oportunidade O3 — "organizar o encontro do time dá trabalho". O convite pronto liga o loop viral 2 (8,84 assentos por sala).',
      whenToUse: 'Primeiro contato de um colaborador que respondeu "Pro meu time" ou "Os dois" na pergunta de persona, ou cujo perfil do gestor indica liderança, RH, assistência executiva.',
      trigger: 'Mesmo gatilho do S-01 (conta criada + opt-in). O ramo Organizador abre a partir da resposta de persona.',
      flow: '(1) apresentação + capacidades de Organizador; (2) tamanho do time; (3) cadência; (4) o que não pode faltar (multi-seleção: tela, café, estacionamento…); (5) local; (6) 3 salas, uma um pouco maior que o pedido; (7) perfil do time; (8) melhor dia → recorrência de 4 datas; (9) convite com endereço e horário para encaminhar.',
      inputs: 'Mesmos atributos do S-01 com onboarding_product = MR, onboarding_frequency ("Sim, 1 vez na semana"), onboarding_amenities (TV,Projector · Coffee · Parking) e o endereço do time; novo atributo sofia_team_size. Serviço extra (coffee, 20+ pessoas, evento) roteia para o Champion de eventos com os 5 campos já coletados (gatilho G2, aba 14).',
      outcome: 'Encontro recorrente criado na 1ª sala e convite pronto para o time — o Organizador não precisa virar gerente de fornecedor.',
      success: 'Métrica principal: % de Organizadores com 4+ reservas em 30 dias da 1ª (hoje 24,9%). Secundárias: recorrência aceita na 1ª sala, participantes que abrem o convite. Trade-off: salas reservadas e não usadas (no-show do grupo).',
    },
    steps: [
      { kind: 'divider', label: 'segunda-feira, 28/09' },
      { kind: 'bot', typing: 900, text: 'Oi, Rafael! Eu sou a **Sofia**, da Woba 👋\n\nSua empresa liberou salas e espaços pra você reunir o time.' },
      { kind: 'info-card', delay: 500,
        title: 'O que eu faço pelo seu time',
        lines: [
          '🔎 **Acho** a sala do tamanho certo, perto de todo mundo',
          '🔁 **Deixo** o encontro recorrente, sem reorganizar tudo',
          '📨 **Envio** o convite com endereço e horário',
          '🎉 **Chamo** o time de eventos pra coffee ou 20+ pessoas',
        ],
      },
      { kind: 'bot', typing: 800, delay: 400, text: 'Me conte 4 coisas sobre os encontros do time. Eu cuido do resto.' },
      { kind: 'quick-replies', delay: 300, items: ['Vamos lá', 'Agora não'] },
      { kind: 'user', delay: 1600, text: 'Vamos lá' },
      { kind: 'bot', typing: 700, text: 'Quantas pessoas costumam participar?' },
      { kind: 'quick-replies', delay: 300, items: ['Até 5', '6 a 10', '11 a 20', 'Mais de 20'] },
      { kind: 'user', delay: 1500, text: '6 a 10' },
      { kind: 'bot', typing: 700, text: 'E com que frequência o time se reúne?' },
      { kind: 'quick-replies', delay: 300, items: ['Toda semana', 'A cada 15 dias', 'Todo mês', 'Só eventos'] },
      { kind: 'user', delay: 1500, text: 'Toda semana' },
      { kind: 'bot', typing: 700, text: 'O que não pode faltar na sala?' },
      { kind: 'open-sheet', delay: 600, sheet: {
        title: 'O que não pode faltar',
        intro: 'Pro encontro dar certo',
        subtitle: 'Marque o essencial. Eu filtro as salas por isso.',
        rows: [
          { label: '☑ Tela ou projetor', value: 'selecionado', accent: 'var(--chat-link)' },
          { label: '☑ Café', value: 'selecionado', accent: 'var(--chat-link)' },
          { label: '☑ Estacionamento perto', value: 'selecionado', accent: 'var(--chat-link)' },
          { label: '☐ Videoconferência' },
          { label: '☐ Lousa' },
          { label: '☐ Acessibilidade' },
        ],
        cta: 'Salvar',
      }},
      { kind: 'flow-submitted', delay: 2200, label: 'Tela, café e estacionamento' },
      { kind: 'bot', typing: 700, text: 'Onde fica melhor pra maioria do time?' },
      { kind: 'user', delay: 1600, text: 'Itaim, perto da Faria Lima' },
      { kind: 'bot', typing: 600, text: 'Deixa eu checar as salas por lá.' },
      { kind: 'bot', typing: 1400, text: 'Separei 3 salas pra 8 pessoas com tela, café e estacionamento 👇\n\nA última cabe 10, se alguém a mais aparecer.' },
      { kind: 'carousel', delay: 300, rooms: [ROOMS.itaim, ROOMS.mrFariaLima, ROOMS.mrJK] },
      { kind: 'info-card', delay: 800,
        title: '✓ Perfil do seu time',
        lines: [
          '👥 6 a 10 pessoas',
          '🔁 Toda semana',
          '🖥️ Tela · ☕ café · 🅿️ estacionamento',
          '📍 Itaim Bibi · Faria Lima',
        ],
        action: 'Editar preferências',
        accent: 'var(--chat-link)',
      },
      { kind: 'bot', typing: 800, delay: 400, text: 'Qual é o melhor dia pro encontro semanal?' },
      { kind: 'quick-replies', delay: 300, items: ['Terça de manhã', 'Quarta de manhã', 'Quinta à tarde'] },
      { kind: 'user', delay: 1600, text: 'Quarta de manhã' },
      { kind: 'open-sheet', delay: 800, sheet: {
        kind: 'recurrence',
        title: 'Encontro semanal do time',
        subtitle: 'WorkBricks Itaim · sala executiva · 8 pessoas',
        origin: '07/10 — Quarta-feira',
        frequencies: [
          { id: 'weekly',   label: 'Semanalmente',   desc: 'Toda semana, cada quarta-feira' },
          { id: 'biweekly', label: 'Quinzenalmente', desc: 'A cada 2 semanas, na quarta-feira' },
          { id: 'monthly',  label: 'Mensalmente',    desc: 'Todo mês, na primeira quarta-feira' },
        ],
        defaultFreq: 'weekly',
        repeatCount: 3,
        preview: [
          { day: 'QUA', dateNum: '07', date: '07/10', month: 'out. 2026', time: '09:00–12:00', origin: true },
          { day: 'QUA', dateNum: '14', date: '14/10', month: 'out. 2026', time: '09:00–12:00' },
          { day: 'QUA', dateNum: '21', date: '21/10', month: 'out. 2026', time: '09:00–12:00' },
          { day: 'QUA', dateNum: '28', date: '28/10', month: 'out. 2026', time: '09:00–12:00' },
        ],
        cta: 'Confirmar 4 reservas',
      }},
      { kind: 'flow-submitted', delay: 2400, label: 'Encontro semanal · 4 quartas' },
      { kind: 'bot', typing: 1000, text: 'Pronto! As próximas 4 quartas estão garantidas na **WorkBricks Itaim** ✅\n\nPra avisar o time, encaminhe este convite 👇' },
      { kind: 'info-card', delay: 400,
        title: '📨 Encontro semanal · Time Rafael',
        lines: [
          '📅 Quartas, a partir de 07/10 · 9h–12h',
          '📍 R. Leopoldo Couto de Magalhães Jr., 700 — Itaim Bibi',
          '🅿️ Estacionamento conveniado no prédio',
          '☕ Café liberado · tela 65"',
        ],
        action: 'Encaminhar convite',
      },
      { kind: 'bot', typing: 800, delay: 600, text: 'Toda terça eu confirmo a sala com você. Se o time crescer, é só me avisar.' },
    ],
  },

  /* ─────────── S-03 — Setup no momento de dor (quem pulou) ─────────── */
  {
    id: 's03', p: 'S-03',
    title: 'Setup no momento de dor',
    category: 'Setup com a Sofia',
    summary: 'Quem pulou o setup não é perguntado de novo no vazio. Quando a dor aparece, a Sofia resolve primeiro e aprende depois — e leva o uso eventual para um dia fixo.',
    color: '#f9e10d',
    startTime: { h: 9, m: 20 },
    spec: {
      purpose: 'Coletar preferências de forma progressiva para quem respondeu "agora não" (36% recusam o onboarding atual). Resolve o pedido urgente numa mensagem (H2) e, depois da visita, faz a transição de caso de uso M1 Contingência → M3 Cadência, que é o trabalho da Sofia segundo o Use Case Map.',
      whenToUse: 'Colaborador com setup pendente que chega com uma dor ("a internet caiu", "a sede lotou", "obra em casa"). Também serve para quem fez só a 1ª reserva e nunca declarou dias.',
      trigger: 'Mensagem do usuário com intenção de urgência. A pergunta de preferência só aparece depois da reserva confirmada e da visita — nunca antes do valor.',
      flow: '(1) respeita o "agora não" e diz como chamar; (2) semanas depois, acolhe a dor e pede só o local; (3) 1 opção livre agora que confirma na hora; (4) reserva e endereço; (5) no dia seguinte pergunta como foi (medida de satisfação que não é ruído); (6) pergunta se a situação se repete; (7) transforma em dia fixo e guarda o favorito.',
      inputs: 'Mesmos atributos do S-01, gravados aos poucos, com sofia_setup_status = skipped → partial → complete. O "agora não" grava onboarding_welcome = 0 mas, diferente do app de hoje, não encerra o setup para sempre. O "como foi?" (nota + motivo) substitui o pedido de feedback atual, com 1,2% de resposta.',
      outcome: 'Uso de contingência vira cadência semanal com perfil mínimo preenchido sem nenhum formulário.',
      success: 'Métrica principal: % dos que pularam o setup com 2+ reservas em 30 dias da 1ª (hoje 44,1% no Individual). Secundárias: taxa de resposta ao "como foi?", % que declara dia fixo. Trade-off: reservas sugeridas canceladas ou no-show.',
    },
    steps: [
      { kind: 'divider', label: 'segunda-feira, 28/09' },
      { kind: 'bot', typing: 900, text: 'Oi, Júlia! Eu sou a **Sofia**, da Woba 👋\n\nSua empresa liberou espaços de trabalho pra você. Posso te fazer 3 perguntas rápidas?' },
      { kind: 'quick-replies', delay: 300, items: ['Vamos lá', 'Agora não'] },
      { kind: 'user', delay: 1600, text: 'Agora não' },
      { kind: 'bot', typing: 800, text: 'Sem problema! Quando precisar de um lugar pra trabalhar, é só me chamar aqui.' },
      { kind: 'divider', delay: 1200, label: 'terça-feira, 13/10' },
      { kind: 'user', delay: 600, text: 'a internet caiu aqui em casa, preciso de um lugar agora' },
      { kind: 'bot', typing: 800, text: 'Que chato ficar sem internet no meio do dia. Vamos resolver agora.' },
      { kind: 'bot', typing: 600, text: 'Onde você está? Envie o bairro ou a sua localização 📍' },
      { kind: 'user', delay: 1500, text: 'Moema' },
      { kind: 'bot', typing: 600, text: 'Deixa eu checar o que está livre agora perto de você.' },
      { kind: 'pill-room', delay: 1200,
        room: ROOMS.wsMoema,
        pill: { text: '📍 5 min · livre agora', dark: true },
        action: 'Reservar agora',
      },
      { kind: 'user', delay: 1800, text: 'Reservar agora' },
      { kind: 'bot', typing: 900, text: 'Sua reserva está confirmada ✅\n\n**Moema Work** · mesa compartilhada\nterça, 13/10 · agora até 18h\n💳 1,5 crédito da sua empresa' },
      { kind: 'location-card', delay: 500,
        title: 'Moema Work',
        address: 'Av. Ibirapuera, 2120 — Moema, São Paulo',
      },
      { kind: 'divider', delay: 1400, label: 'quarta-feira, 14/10' },
      { kind: 'bot', typing: 800, text: 'Oi, Júlia! Como foi ontem na **Moema Work**?' },
      { kind: 'quick-replies', delay: 300, items: ['Foi ótimo', 'Teve problema'] },
      { kind: 'user', delay: 1500, text: 'Foi ótimo' },
      { kind: 'bot', typing: 800, text: 'Que bom! Isso costuma acontecer ou foi só ontem?' },
      { kind: 'quick-replies', delay: 300, items: ['Foi só ontem', 'Às vezes', 'Queria ir toda semana'] },
      { kind: 'user', delay: 1600, text: 'Queria ir toda semana' },
      { kind: 'bot', typing: 700, text: 'Boa! Qual dia fica melhor pra você?' },
      { kind: 'quick-replies', delay: 300, items: ['Segunda', 'Quarta', 'Sexta'] },
      { kind: 'user', delay: 1500, text: 'Quarta' },
      { kind: 'info-card', delay: 600,
        title: '✓ Seu perfil com a Sofia',
        lines: [
          '📍 Moema',
          '📅 Quartas',
          '⭐ Moema Work como seu lugar',
          '🆘 Emergência? Me chame que eu acho outro',
        ],
        action: 'Editar preferências',
        accent: 'var(--chat-link)',
      },
      { kind: 'bot', typing: 900, delay: 400, text: 'Anotado! Toda terça à noite eu te mostro a mesa de quarta.\n\nÉ só confirmar com 1 toque.' },
    ],
  },


  /* ─────────── P-01 — Check-in proativo via deeplink ─────────── */
  {
    id: 'p01', p: 'P-01',
    title: 'Check-in proativo',
    category: 'Pré-reunião',
    summary: '15 min antes, deeplink que abre o app e tenta check-in automático (geofence + BLE).',
    color: '#81c42b',
    startTime: { h: 9, m: 44 },
    steps: [
      { kind: 'divider', label: 'Hoje' },
      { kind: 'bot', typing: 900, text: 'Sua reunião na **Tribbos Coworking** começa em 15 min 👋\n\nToque pra fazer seu **check-in** direto no app — vai automático assim que você chegar.' },
      { kind: 'info-card', delay: 400,
        title: '↗ Fazer check-in no app',
        lines: [],
        accent: 'var(--chat-link)',
      },
      { kind: 'user', delay: 1500, text: '[ toca em "Fazer check-in" ]' },
      { kind: 'divider', delay: 600, label: '↗ abrindo app Woba…', color: 'link' },
      { kind: 'app-screen', delay: 800,
        title: 'Check-in · sala 02',
        lines: ['Verificando localização…', 'Procurando beacon…'],
        success: '✓ Check-in automático',
      },
      { kind: 'bot', typing: 1000, delay: 1500, text: 'Tudo certo, check-in feito ✅\n\nAproveite a reunião. Te procuro de novo no fim, ok?' },
    ],
  },

  /* ─────────── P-02 — Huddle SOS ─────────── */
  {
    id: 'p02', p: 'P-02',
    title: 'Huddle SOS — sala agora',
    category: 'Reserva expressa',
    summary: '"Preciso de sala agora." Card único, sem Flow, confirmação em 1 toque.',
    color: '#fe8c14',
    startTime: { h: 14, m: 30 },
    steps: [
      { kind: 'user', text: 'preciso de uma sala agora pra 4 pessoas' },
      { kind: 'bot', typing: 900, text: 'Bora resolver 💨\n\nAchei a **mais perto disponível agora**:' },
      { kind: 'pill-room', delay: 300,
        room: ROOMS.vila,
        pill: { text: '📍 8 min a pé', dark: true },
        action: 'Confirmar 1h',
      },
      { kind: 'bot', delay: 600, text: '6 pessoas · livre por 2h · 8,5 créd/h' },
      { kind: 'user', delay: 1800, text: 'Confirmar 1h' },
      { kind: 'bot', typing: 800, text: 'Reservado ✅\nVila Olímpia · 14:32–15:32' },
      { kind: 'quick-replies', delay: 400, items: ['Abrir Maps', 'Avisar o time'] },
    ],
  },

  /* ─────────── P-03 — Recorrência inteligente ─────────── */
  {
    id: 'p03', p: 'P-03',
    title: 'Recorrência inteligente',
    category: 'Padrão de uso',
    summary: 'Detecta padrão após 3 reservas e oferece travar a série toda semana.',
    color: '#a768ff',
    startTime: { h: 17, m: 0 },
    steps: [
      { kind: 'divider', label: 'segunda-feira' },
      { kind: 'bot', typing: 900, text: 'Reparei que você reserva a **sala 02 do Tribbos** toda **terça às 10h**.\n\nQuer que eu já deixe travada toda semana? Você cancela quando quiser.' },
      { kind: 'quick-replies', delay: 600, items: ['Sim, boa ideia', 'Hmm, agora não'] },
      { kind: 'user', delay: 2000, text: 'Sim, boa ideia' },
      { kind: 'open-sheet', delay: 800, sheet: {
        kind: 'recurrence',
        title: 'Repetir esta reserva',
        subtitle: 'Configure as datas recorrentes',
        origin: '27/05 — Terça-feira',
        frequencies: [
          { id: 'weekly',   label: 'Semanalmente',  desc: 'Toda semana, cada terça-feira' },
          { id: 'biweekly', label: 'Quinzenalmente', desc: 'A cada 2 semanas, na terça-feira' },
          { id: 'monthly',  label: 'Mensalmente',    desc: 'Todo mês, na última terça-feira' },
          { id: 'weekdays', label: 'Dias úteis',     desc: 'Todos os dias da semana (seg–sex)' },
        ],
        defaultFreq: 'weekly',
        repeatCount: 3,
        preview: [
          { day: 'TER', dateNum: '27', date: '27/05', month: 'mai. 2026', time: '10:00–12:00', origin: true },
          { day: 'TER', dateNum: '03', date: '03/06', month: 'jun. 2026', time: '10:00–12:00' },
          { day: 'TER', dateNum: '10', date: '10/06', month: 'jun. 2026', time: '10:00–12:00', unavailable: true },
          { day: 'TER', dateNum: '17', date: '17/06', month: 'jun. 2026', time: '10:00–12:00' },
        ],
        cta: 'Confirmar 4 reservas',
      }},
      { kind: 'flow-submitted', delay: 2200, label: 'Reserva recorrente com sucesso' },
      { kind: 'bot', typing: 1000, text: 'Pronto! Sua mesa fixa de terça está garantida pelas próximas **12 semanas** 🎯\n\nToda segunda às 17h te lembro. Se algum dia não rolar, é só me dizer.' },
    ],
  },

  /* ─────────── P-04 — Avisar quem vai com você ─────────── */
  {
    id: 'p04', p: 'P-04',
    title: 'Avise quem vai com você',
    category: 'Pós-reserva',
    summary: 'Após reservar, oferece chamar convidados 1-on-1 com painel de RSVP atualizando.',
    color: '#3a80ce',
    startTime: { h: 10, m: 2 },
    steps: [
      { kind: 'bot', text: 'Reserva confirmada ✅\nTribbos · sala 02 · 10:00' },
      { kind: 'bot', delay: 600, typing: 700, text: 'Quer que eu já avise quem vai com você?' },
      { kind: 'quick-replies', delay: 300, items: ['Sim, avisar', 'Eu mando depois'] },
      { kind: 'user', delay: 1800, text: 'Sim, avisar' },
      { kind: 'open-sheet', delay: 800, sheet: {
        title: 'Quem você vai chamar?',
        subtitle: 'Sugerido pelo evento do Calendar',
        rows: [
          { label: '☑ Joana Maciel', value: 'sugerida' },
          { label: '☑ Pedro Silva',  value: 'sugerido' },
          { label: '☐ Marcelo Reis', value: 'opcional' },
          { label: '+ Adicionar contato', cta: 'Buscar' },
        ],
        cta: 'Enviar pra 3 pessoas',
      }},
      { kind: 'flow-submitted', delay: 2200, label: 'Enviar para 3 pessoas' },
      { kind: 'bot', typing: 900, text: 'Mandei pra 3 pessoas 📨\n\nTe aviso aqui mesmo conforme elas confirmarem.' },
      { kind: 'rsvp-card', delay: 2000,
        items: [
          { name: 'Joana',   s: 'pending' },
          { name: 'Pedro',   s: 'pending' },
          { name: 'Marcelo', s: 'pending' },
        ],
      },
      { kind: 'rsvp-card', delay: 2500,
        items: [
          { name: 'Joana',   s: 'yes' },
          { name: 'Pedro',   s: 'pending' },
          { name: 'Marcelo', s: 'yes' },
        ],
      },
    ],
  },

  /* ─────────── P-05 — Estender reunião ─────────── */
  {
    id: 'p05', p: 'P-05',
    title: 'Estende sua reunião',
    category: 'Durante a reunião',
    summary: 'T-5min do fim — sala segue livre? 3 chips +15/+30/+1h, 1 toque, sem app.',
    color: '#25c265',
    startTime: { h: 10, m: 55 },
    steps: [
      { kind: 'bot', typing: 900, text: 'Sua reunião acaba em **5 min** ⏱️\n\nA sala segue livre por mais 1h. Quer estender?' },
      { kind: 'quick-replies', delay: 300, items: ['+15 min', '+30 min', '+1h', 'Tô finalizando'] },
      { kind: 'user', delay: 1800, text: '+30 min' },
      { kind: 'bot', typing: 800, text: 'Estendido! ✅ Reserva vai até **11:00** agora.\n\nTe aviso de novo perto do fim, ok?' },
    ],
  },

  /* ─────────── P-06 — Falar com a gente ─────────── */
  {
    id: 'p06', p: 'P-06',
    title: 'Falar com a gente (suporte)',
    category: 'Pós-reserva permanente',
    summary: 'Botão fixo no card de confirmação. Triagem por chips, escalation com SLA.',
    color: '#ec4899',
    startTime: { h: 10, m: 18 },
    steps: [
      { kind: 'info-card', title: 'Reserva confirmada ✅',
        lines: ['Tribbos · sala 02', '10:00–11:00'],
        action: '🛠️ Problema com a sala? Fale com a gente',
      },
      { kind: 'user', delay: 1800, text: '[ toca em Fale com a gente ]' },
      { kind: 'bot', typing: 900, text: 'Tô aqui pra ajudar 👋\n\nMe conta rapidinho o que tá rolando?' },
      { kind: 'quick-replies', delay: 300, items: ['Sala suja', 'Equipamento quebrado', 'Não consigo entrar', 'Outro'] },
      { kind: 'user', delay: 1800, text: 'Equipamento quebrado' },
      { kind: 'bot', typing: 700, text: 'Qual equipamento?' },
      { kind: 'quick-replies', delay: 300, items: ['🖥️ TV', '📶 Wi-Fi', '❄️ Ar', '💺 Cadeiras'] },
      { kind: 'user', delay: 1800, text: '🖥️ TV' },
      { kind: 'bot', typing: 900, text: 'Anotado: **TV quebrada**.\n\nTô chamando alguém do Tribbos agora 📞\nTempo médio: **4 min** ⏱️\n\nPrefere resolver por aqui ou recebe ligação?' },
      { kind: 'quick-replies', delay: 300, items: ['Aqui mesmo', 'Pode ligar'] },
    ],
  },

  /* ─────────── P-07 — Sala substituta ─────────── */
  {
    id: 'p07', p: 'P-07',
    title: 'Sala substituta automática',
    category: 'Imprevisto',
    summary: 'Coworking cancela; Sofia já chega com 3 alternativas equivalentes.',
    color: '#de6530',
    startTime: { h: 9, m: 32 },
    steps: [
      { kind: 'bot', typing: 900, text: '⚠️ Olha, o Tribbos avisou agora que sua sala das **10h** não vai dar.\n\nJá procurei e achei **3 alternativas perto** pra você 👇' },
      { kind: 'room', delay: 400, room: ROOMS.vila },
      { kind: 'room', delay: 200, room: ROOMS.itaim },
      { kind: 'room', delay: 200, room: ROOMS.pinheiros },
      { kind: 'bot', delay: 500, text: 'Mantive seu horário (10h–11h) e capacidade (5 pessoas). É só escolher.' },
    ],
  },

  /* ─────────── P-08 — Visita externa ─────────── */
  {
    id: 'p08', p: 'P-08',
    title: 'Pré-cadastro de visitantes',
    category: 'Pré-reunião',
    summary: 'Sofia pergunta se tem visita externa e cuida do cadastro na portaria.',
    color: '#a768ff',
    startTime: { h: 10, m: 3 },
    steps: [
      { kind: 'bot', text: 'Reserva confirmada ✅' },
      { kind: 'bot', delay: 600, typing: 700, text: 'Vai ter **visita de fora** nessa reunião?' },
      { kind: 'quick-replies', delay: 300, items: ['Sim', 'Não', 'Avise depois'] },
      { kind: 'user', delay: 1800, text: 'Sim, 2 visitantes' },
      { kind: 'open-sheet', delay: 800, sheet: {
        title: 'Cadastro de visitantes',
        subtitle: 'Visitante 1 de 2 · Tribbos',
        rows: [
          { label: '👤 Nome', value: 'João Pereira' },
          { label: '📄 Documento', value: '12345678-9' },
          { label: '🏢 Empresa', value: 'opcional' },
          { label: '📷 Foto', cta: '+ Tirar' },
          { label: '+ Próximo visitante', cta: 'Adicionar' },
        ],
        cta: 'Mandar pra recepção',
      }},
      { kind: 'flow-submitted', delay: 2400, label: 'Cadastrar 2 visitantes' },
      { kind: 'bot', typing: 1000, text: 'Tudo certo! ✅\n\nMandei pra recepção do **Tribbos**. **João** e **Marcelo** são esperados — só precisam mostrar documento.' },
    ],
  },

  /* ─────────── P-09 — Review pós-reunião ─────────── */
  {
    id: 'p09', p: 'P-09',
    title: 'Review pós-reunião',
    category: 'Pós-reunião',
    summary: '30 min depois: 🙂/😐/🙁 + categoria. Alimenta ranking de salas.',
    color: '#3a80ce',
    startTime: { h: 11, m: 32 },
    steps: [
      { kind: 'bot', typing: 900, text: 'E aí, como foi sua reunião na **Tribbos sala 02**? 👀' },
      { kind: 'quick-replies', delay: 300, items: ['🙂 Boa', '😐 Ok', '🙁 Ruim'] },
      { kind: 'user', delay: 2000, text: '😐 Ok' },
      { kind: 'bot', typing: 700, text: 'O que poderia ter sido melhor? *(opcional)*' },
      { kind: 'quick-replies', delay: 300, items: ['Limpeza', 'Equipamento', 'Som', 'Temperatura', 'Outro'] },
      { kind: 'user', delay: 1800, text: 'Temperatura' },
      { kind: 'bot', typing: 900, text: 'Ouvido 🙏 Já marquei essa observação na **sala 02** — quem reservar depois vai saber.\n\nSe acontecer de novo, é só me chamar.' },
    ],
  },

  /* ─────────── P-10 — Campanhas temáticas ─────────── */
  {
    id: 'p10', p: 'P-10',
    title: 'Campanhas temáticas',
    category: 'Engajamento',
    summary: 'Sazonalidade vira conversa, não banner. "Segunda fria daquelas ☁️".',
    color: '#f9e10d',
    startTime: { h: 9, m: 5 },
    steps: [
      { kind: 'bot', typing: 900, text: 'Segunda fria daquelas ☁️\n\nAchei 3 salas perto com **café cortesia** essa semana 👇' },
      { kind: 'pill-room', delay: 400,
        room: ROOMS.tribbos,
        pill: { text: '☕ Café cortesia' },
        action: 'Reservar',
      },
      { kind: 'pill-room', delay: 200,
        room: ROOMS.vila,
        pill: { text: '☕ Café cortesia' },
        action: 'Reservar',
      },
      { kind: 'pill-room', delay: 200,
        room: ROOMS.pinheiros,
        pill: { text: '☕ Café cortesia' },
        action: 'Reservar',
      },
      { kind: 'bot', delay: 500, text: 'Se nenhuma servir, é só me chamar 💛' },
    ],
  },

  /* ─────────── P-11 — Boas-vindas / Onboarding ─────────── */
  {
    id: 'p11', p: 'P-11',
    title: 'Boas-vindas',
    category: 'Onboarding',
    summary: '1ª mensagem após cadastro. 3 bullets do que faz + convite pra reservar.',
    color: '#f9e10d',
    startTime: { h: 10, m: 14 },
    steps: [
      { kind: 'divider', label: 'Hoje' },
      { kind: 'bot', typing: 900, text: 'Oi, **Marina**! 👋 Bem-vinda à Woba.\n\nEu sou a **Sofia**, sua assistente. Aqui pelo WhatsApp eu cuido de:\n\n🪑 **Achar e reservar salas** em qualquer coworking parceiro\n📅 **Lembrar você** antes e depois da reunião\n🛠️ **Resolver problemas** se algo não rolar na sala' },
      { kind: 'quick-replies', delay: 600, items: ['Reservar uma sala', 'Como funciona?', 'Depois eu vejo'] },
    ],
  },

  /* ─────────── P-12 — Re-engagement D+7 ─────────── */
  {
    id: 'p12', p: 'P-12',
    title: 'Re-engagement personalizado',
    category: 'Re-engajamento',
    summary: '7 dias sem reservar — sugestão baseada no histórico, com saída de respeito.',
    color: '#fe8c14',
    startTime: { h: 9, m: 12 },
    steps: [
      { kind: 'divider', label: 'terça-feira' },
      { kind: 'bot', typing: 900, text: 'Oi! Essa semana você ainda não reservou nada por aqui 👀\n\nReparei que você costuma reservar **Tribbos quartas de manhã**. A **sala 02** tá livre essa quarta no mesmo horário 👇' },
      { kind: 'pill-room', delay: 400,
        room: ROOMS.tribbos,
        pill: { text: '✨ Sua escolha frequente' },
        action: '📋 Reservar essa',
      },
      { kind: 'quick-replies', delay: 400, items: ['Outro horário', 'Outra sala', 'Tô fora essa semana'] },
    ],
  },

  /* ─────────── P-13 — Reservar de novo ─────────── */
  {
    id: 'p13', p: 'P-13',
    title: 'Reservar de novo',
    category: 'Atalho',
    summary: 'Saudação oferece as 3 últimas reservas como atalho — Flow já preenchido.',
    color: '#a768ff',
    startTime: { h: 14, m: 8 },
    steps: [
      { kind: 'user', text: 'oi' },
      { kind: 'bot', typing: 800, text: 'Oi, **Marina**! 👋\n\nQuer repetir alguma das suas últimas reservas? 👇' },
      { kind: 'pill-room', delay: 400,
        room: ROOMS.tribbos,
        pill: { text: '🕒 há 3 dias', dark: true },
        action: '🔄 Reservar de novo',
      },
      { kind: 'pill-room', delay: 200,
        room: ROOMS.vila,
        pill: { text: '🕒 semana passada', dark: true },
        action: '🔄 Reservar de novo',
      },
      { kind: 'pill-room', delay: 200,
        room: ROOMS.itaim,
        pill: { text: '🕒 há 2 semanas', dark: true },
        action: '🔄 Reservar de novo',
      },
      { kind: 'quick-replies', delay: 400, items: ['Buscar nova', 'Outro horário'] },
    ],
  },

  /* ─────────── P-14 — Chamado técnico (privativo) ─────────── */
  {
    id: 'p14', p: 'P-14',
    title: 'Chamado técnico — privativo',
    category: 'Operação',
    summary: 'Linguagem natural → Flow estruturado → ticket com SLA + updates async.',
    color: '#de6530',
    startTime: { h: 15, m: 42 },
    steps: [
      { kind: 'user', text: 'ar condicionado parou de novo' },
      { kind: 'bot', typing: 900, text: 'Vou abrir um chamado pro **Tribbos** agora.\n\nMe ajuda com 3 coisas rapidinhas?' },
      { kind: 'open-sheet', delay: 800, sheet: {
        title: 'Abrir chamado',
        intro: 'Tribbos · Escritório privativo',
        rows: [
          { label: '🔥 Severidade', value: 'Alto ●', accent: 'var(--chat-link)', bold: true },
          { label: '📍 Local', value: 'Sala 2' },
          { label: '📷 Foto', cta: '+ Anexar' },
          { label: '📝 Descrição', value: 'opcional' },
        ],
        cta: 'Abrir chamado',
      }},
      { kind: 'flow-submitted', delay: 2600, label: 'Abrir chamado · TV quebrada' },
      { kind: 'ticket-card', delay: 600, id: '#2143', severity: 'Alto', eta: '2h', status: 'aberto' },
      { kind: 'bot', typing: 1200, delay: 1800, text: 'Atualização do **#2143**:\n\n👷 **Marcelo** do time do Tribbos confirmou. Ele tá indo aí agora.\n⏱️ Chegada estimada: 15 min' },
    ],
  },

  /* ─────────── P-15 — FAQ / dúvidas operacionais (Nível 1) ─────────── */
  {
    id: 'p15', p: 'P-15',
    title: 'FAQ — autoatendimento Nível 1',
    category: 'Suporte',
    summary: 'Base de conhecimento conversacional. "Como funciona", "qual prazo", "onde acho".',
    color: '#3a80ce',
    startTime: { h: 13, m: 22 },
    steps: [
      { kind: 'user', text: 'como funciona os créditos?' },
      { kind: 'bot', typing: 1000, text: 'Boa pergunta! 💛\n\n**Créditos Woba** funcionam assim:\n\n💳 Cada plano libera créditos por mês\n⏱️ Você usa em qualquer coworking parceiro\n🔄 Sobrou? Acumula até o mês seguinte (limite de 50%)\n📅 Reservas canceladas até 2h antes devolvem o crédito\n\nQuer ver seu saldo atual?' },
      { kind: 'info-card', delay: 400,
        title: '↗ Ver detalhes no app',
        lines: ['`woba://carteira/creditos`', 'Saldo, extrato e plano'],
        accent: 'var(--chat-link)',
      },
      { kind: 'quick-replies', delay: 400, items: ['Resolvi 👍', 'Falar com humano', 'Outra dúvida'] },
      { kind: 'user', delay: 2200, text: 'Resolvi 👍' },
      { kind: 'bot', typing: 700, text: 'Show! Se aparecer outra dúvida, é só me chamar 💛\n\n📚 Você pode ler mais em: dúvidas frequentes' },
    ],
  },

  /* ─────────── P-16 — Consultar minha reserva ─────────── */
  {
    id: 'p16', p: 'P-16',
    title: 'Onde é minha próxima reunião?',
    category: 'Self-service',
    summary: 'Lê dados da reserva e responde em linguagem natural — endereço, horário, capacidade.',
    color: '#81c42b',
    startTime: { h: 8, m: 14 },
    steps: [
      { kind: 'user', text: 'onde é minha próxima reunião?' },
      { kind: 'bot', typing: 900, text: 'Sua próxima reunião é hoje às **10h** na **Tribbos Coworking** 👇' },
      { kind: 'location-card', delay: 400,
        title: 'Tribbos Coworking',
        address: 'Av. Marechal Floriano Peixoto, 720 — Centro',
        mapImage: 'assets/map-1.svg',
      },
      { kind: 'bot', delay: 500, text: 'Sala 02 · 2º andar · capacidade pra 5 pessoas.' },
      { kind: 'quick-replies', delay: 400, items: ['Como chegar', 'Capacidade', 'Convidados', 'Trocar local'] },
      { kind: 'user', delay: 2000, text: 'Convidados' },
      { kind: 'bot', typing: 800, text: 'Você convidou 3 pessoas:' },
      { kind: 'rsvp-card', delay: 400,
        items: [
          { name: 'Joana Maciel', s: 'yes' },
          { name: 'Pedro Silva',  s: 'pending' },
          { name: 'Marcelo Reis', s: 'yes' },
        ],
      },
    ],
  },

  /* ─────────── P-17 — Cancelar reserva ─────────── */
  {
    id: 'p17', p: 'P-17',
    title: 'Cancelar reserva',
    category: 'Self-service',
    summary: 'Identifica a reserva, pergunta motivo opcional, devolve créditos visivelmente.',
    color: '#de6530',
    startTime: { h: 16, m: 4 },
    steps: [
      { kind: 'user', text: 'preciso cancelar a reserva de amanhã' },
      { kind: 'bot', typing: 900, text: 'Achei aqui 👇' },
      { kind: 'info-card', delay: 400,
        title: 'Tribbos · sala 02',
        lines: ['Amanhã · 10:00–12:00', '5 pessoas · 14 créditos'],
      },
      { kind: 'bot', delay: 500, text: 'Cancelando agora você **recebe os 14 créditos de volta** (ainda tá no prazo).\n\nQuer continuar?' },
      { kind: 'quick-replies', delay: 400, items: ['Sim, cancelar', 'Não, vou manter'] },
      { kind: 'user', delay: 2000, text: 'Sim, cancelar' },
      { kind: 'open-sheet', delay: 600, sheet: {
        title: 'Cancelar reserva',
        intro: 'Tribbos · sala 02',
        subtitle: 'Amanhã · 10:00–12:00',
        rows: [
          { label: '💳 Créditos a devolver', value: '14 créd', accent: 'var(--chat-link)', bold: true },
          { label: '📝 Motivo', value: 'opcional' },
          { label: '🔔 Avisar convidados?', value: 'Sim ●', accent: 'var(--chat-link)' },
        ],
        cta: 'Cancelar reserva',
      }},
      { kind: 'flow-submitted', delay: 2400, label: 'Cancelar reserva' },
      { kind: 'bot', typing: 900, text: 'Reserva cancelada ✅\n\n💳 **14 créditos** voltaram pra sua carteira\n📨 Joana, Pedro e Marcelo foram avisados\n\nSe precisar marcar outra, é só falar comigo 💛' },
    ],
  },

  /* ─────────── P-18 — Remarcar reserva ─────────── */
  {
    id: 'p18', p: 'P-18',
    title: 'Remarcar reserva',
    category: 'Self-service',
    summary: 'Mantém a mesma sala, desliza pra outra data. Avisa os convidados automaticamente.',
    color: '#a768ff',
    startTime: { h: 9, m: 32 },
    steps: [
      { kind: 'user', text: 'quero mudar a reunião de amanhã pra quinta' },
      { kind: 'bot', typing: 900, text: 'Entendi! Sua reunião era:\n\n**Tribbos · sala 02**\n📅 Amanhã (quarta) · 10:00–12:00\n\nQuer manter o mesmo horário (10h–12h) na **quinta**?' },
      { kind: 'quick-replies', delay: 400, items: ['Sim, quinta 10h', 'Outro horário', 'Cancela então'] },
      { kind: 'user', delay: 2000, text: 'Sim, quinta 10h' },
      { kind: 'bot', typing: 800, text: 'Vou checar se a sala 02 tá livre na quinta…' },
      { kind: 'bot', typing: 1100, delay: 1500, text: 'Boa notícia: **livre** 🎯\n\nConfirmo a troca pra quinta 10h-12h?' },
      { kind: 'open-sheet', delay: 700, sheet: {
        title: 'Remarcar reserva',
        intro: 'Tribbos · sala 02',
        subtitle: 'De quarta → quinta · 10:00–12:00',
        rows: [
          { label: '📅 Nova data', value: 'Quinta · 23/05', accent: 'var(--chat-link)', bold: true },
          { label: '⏰ Horário', value: '10:00–12:00' },
          { label: '💳 Créditos', value: 'mantidos · 14' },
          { label: '🔔 Avisar convidados?', value: 'Sim ●', accent: 'var(--chat-link)' },
        ],
        cta: 'Confirmar remarcação',
      }},
      { kind: 'flow-submitted', delay: 2600, label: 'Confirmar remarcação' },
      { kind: 'bot', typing: 900, text: 'Pronto! ✅\n\n📅 Agora é **quinta às 10h** na **Tribbos sala 02**\n📨 Já avisei Joana, Pedro e Marcelo com o novo horário\n\nTe lembro na quarta à noite 👋' },
    ],
  },

  /* ─────────── P-19 — Trocar local da reserva ─────────── */
  {
    id: 'p19', p: 'P-19',
    title: 'Trocar de local',
    category: 'Self-service',
    summary: 'Mesma data e horário, outra sala. 3 alternativas equivalentes — visual rich.',
    color: '#fe8c14',
    startTime: { h: 14, m: 50 },
    steps: [
      { kind: 'user', text: 'essa sala da Tribbos não tá legal, dá pra trocar pra outra perto?' },
      { kind: 'bot', typing: 1000, text: 'Claro! Vou manter seu **horário (10h–12h)** e **5 pessoas**, e te mostro 3 alternativas perto 👇' },
      { kind: 'pill-room', delay: 400,
        room: ROOMS.vila,
        pill: { text: '✨ Mais bem avaliada' },
        action: '🔄 Trocar pra essa',
      },
      { kind: 'pill-room', delay: 200,
        room: ROOMS.itaim,
        pill: { text: '📍 Mais perto', dark: true },
        action: '🔄 Trocar pra essa',
      },
      { kind: 'pill-room', delay: 200,
        room: ROOMS.pinheiros,
        pill: { text: '💳 Mesmo crédito', dark: true },
        action: '🔄 Trocar pra essa',
      },
      { kind: 'bot', delay: 500, text: 'Quando você escolher, eu cancelo a anterior e mando o novo endereço pros convidados.' },
    ],
  },

  /* ─────────── N-06A — CSAT do agente (positivo) ─────────── */
  {
    id: 'n06a', p: 'N-06A',
    title: 'CSAT — conversa resolvida',
    category: 'Pós-atendimento',
    summary: 'Após resolver qualquer assunto, Sofia pergunta se conseguiu ajudar. Caminho positivo com encerramento limpo.',
    color: '#25c265',
    startTime: { h: 11, m: 14 },
    steps: [
      { kind: 'bot', text: 'Reserva confirmada ✅\n**Tribbos** · sala 02 · amanhã 10h–12h' },
      { kind: 'bot', delay: 900, typing: 600, text: 'Consegui te ajudar com isso? 😊' },
      { kind: 'quick-replies', delay: 300, items: ['Sim, resolveu 👍', 'Não totalmente'] },
      { kind: 'user', delay: 2000, text: 'Sim, resolveu 👍' },
      { kind: 'bot', typing: 600, text: 'Que ótimo! 💛 Qualquer outra coisa, é só me chamar.' },
    ],
  },

  /* ─────────── N-06B — CSAT do agente (negativo) ─────────── */
  {
    id: 'n06b', p: 'N-06B',
    title: 'CSAT — não resolvido',
    category: 'Pós-atendimento',
    summary: 'CSAT negativo com chips de motivo. Usuário sinaliza o que faltou — alimenta melhoria contínua do agente.',
    color: '#de6530',
    startTime: { h: 15, m: 40 },
    steps: [
      { kind: 'bot', text: 'Encaminhei sua dúvida pro time de suporte 📨\nEles te retornam em até **8 min**.' },
      { kind: 'bot', delay: 900, typing: 600, text: 'Consegui te ajudar com isso? 😊' },
      { kind: 'quick-replies', delay: 300, items: ['Sim, resolveu 👍', 'Não totalmente'] },
      { kind: 'user', delay: 2000, text: 'Não totalmente' },
      { kind: 'bot', typing: 700, text: 'Que pena 😕\n\nO que eu poderia ter feito melhor? *(opcional)*' },
      { kind: 'quick-replies', delay: 300, items: ['Resposta incompleta', 'Demorou demais', 'Não entendeu o problema', 'Outro motivo'] },
      { kind: 'user', delay: 2000, text: 'Resposta incompleta' },
      { kind: 'bot', typing: 900, text: 'Obrigada pelo feedback 🙏 Vou usar isso pra melhorar.\n\nSe ainda precisar, pode me chamar ou falar direto com o suporte.' },
    ],
  },

  /* ─────────── H-01 — Histórico · última reserva ─────────── */
  {
    id: 'h01', p: 'H-01',
    title: 'Última reserva',
    category: 'Histórico & Preferências',
    summary: 'Usuário pergunta sobre a última reserva — Sofia responde com card e oferece reservar de novo.',
    color: '#3a80ce',
    startTime: { h: 9, m: 8 },
    steps: [
      { kind: 'user', text: 'qual foi minha última reserva?' },
      { kind: 'bot', typing: 900, text: 'Achei aqui 👇' },
      { kind: 'info-card', delay: 400,
        title: 'Tribbos Coworking · sala 02',
        lines: ['📅 14/05 · semana passada · 10:00–12:00', '👥 5 pessoas · 14 créditos', '✅ Check-in realizado'],
      },
      { kind: 'bot', delay: 500, text: 'Quer reservar o mesmo espaço de novo?' },
      { kind: 'quick-replies', delay: 300, items: ['Reservar de novo', 'Ver histórico completo', 'Não, obrigado'] },
      { kind: 'user', delay: 2000, text: 'Reservar de novo' },
      { kind: 'bot', typing: 800, text: 'Boa! Para quando? Posso manter o mesmo horário (**10h–12h**)?' },
      { kind: 'quick-replies', delay: 300, items: ['Amanhã 10h', 'Essa semana', 'Outra data'] },
    ],
  },

  /* ─────────── H-02 — Histórico · espaços favoritos ─────────── */
  {
    id: 'h02', p: 'H-02',
    title: 'Espaços favoritos',
    category: 'Histórico & Preferências',
    summary: 'Sofia analisa o padrão das últimas reservas e revela o top 3 de coworkings e a janela horária preferida.',
    color: '#a768ff',
    startTime: { h: 13, m: 22 },
    steps: [
      { kind: 'user', text: 'onde eu mais costumo reservar?' },
      { kind: 'bot', typing: 1100, text: 'Analisei suas últimas **12 reservas**. Veja seu padrão 👇' },
      { kind: 'info-card', delay: 400,
        title: '📊 Seus espaços mais frequentes',
        lines: [
          '🥇 Tribbos Coworking — 5 reservas',
          '🥈 Vila Olímpia Hub — 4 reservas',
          '🥉 WorkBricks Itaim — 3 reservas',
        ],
      },
      { kind: 'bot', delay: 500, text: '**Terças de manhã** são sua janela mais frequente ⏰\n\nQuer reservar em algum deles agora?' },
      { kind: 'quick-replies', delay: 300, items: ['Tribbos', 'Vila Olímpia', 'Itaim', 'Buscar outro'] },
    ],
  },

  /* ─────────── H-03 — Histórico · consumo de créditos ─────────── */
  {
    id: 'h03', p: 'H-03',
    title: 'Consumo de créditos',
    category: 'Histórico & Preferências',
    summary: 'Sofia puxa o extrato do mês atual e projeta quantas reservas ainda cabem no saldo restante.',
    color: '#fe8c14',
    startTime: { h: 16, m: 44 },
    steps: [
      { kind: 'user', text: 'quanto crédito eu usei esse mês?' },
      { kind: 'bot', typing: 1000, text: 'Puxando seu extrato de maio 2026…' },
      { kind: 'info-card', delay: 700,
        title: '💳 Extrato · maio 2026',
        lines: [
          'Reservas realizadas: 6',
          'Créditos usados: 48 de 80',
          'Créditos restantes: 32',
          'Maior uso: Tribbos (21 créd.)',
          'Renovação: 01/06/2026',
        ],
      },
      { kind: 'bot', delay: 400, text: 'Você ainda tem **32 créditos** — dá pra mais 4 reservas no seu padrão de uso.\n\nO plano renova em **01/06**.' },
      { kind: 'quick-replies', delay: 300, items: ['Ver extrato no app', 'Reservar agora', 'Entendido 👍'] },
    ],
  },

  /* ─────────── H-04 — Histórico · salvar preferência ─────────── */
  {
    id: 'h04', p: 'H-04',
    title: 'Salvar preferência',
    category: 'Histórico & Preferências',
    summary: 'Usuário define região e capacidade padrão para buscas futuras. Sofia confirma, salva e aplica na próxima busca.',
    color: '#81c42b',
    startTime: { h: 10, m: 5 },
    steps: [
      { kind: 'user', text: 'quero que você me sugira sempre salas em Pinheiros pra até 5 pessoas' },
      { kind: 'bot', typing: 1000, text: 'Anotado! ✍️ Vou guardar como sua preferência padrão:' },
      { kind: 'info-card', delay: 400,
        title: '⭐ Preferência salva',
        lines: [
          '📍 Região: Pinheiros, São Paulo',
          '👥 Capacidade: até 5 pessoas',
        ],
      },
      { kind: 'bot', delay: 500, text: 'Da próxima vez que você pedir uma sala sem especificar o local, começo por **Pinheiros**.\n\nQuer adicionar mais alguma preferência?' },
      { kind: 'quick-replies', delay: 300, items: ['Adicionar horário fixo', 'Mudar região', 'Tá ótimo, obrigado!'] },
      { kind: 'user', delay: 2000, text: 'Tá ótimo, obrigado!' },
      { kind: 'bot', typing: 600, text: 'Show! 💛 Preferências salvas. Próxima busca já vai ser mais rápida.' },
    ],
  },

  /* ─────────── I-04 — Reservar por voz ─────────── */
  {
    id: 'i04', p: 'I-04',
    title: 'Reservar por voz',
    category: 'Ideação · em proto',
    summary: 'Aperta o microfone, fala "sala pra 4 em Pinheiros amanhã 14h" — Sofia entende.',
    color: '#a768ff',
    startTime: { h: 18, m: 32 },
    steps: [
      { kind: 'voice-message', side: 'user', duration: '0:09' },
      { kind: 'bot', typing: 1200, text: '🎙️ Transcrevendo…' },
      { kind: 'info-card', delay: 1000,
        title: '🎙️ Você falou:',
        lines: ['"preciso de uma sala pra 4 pessoas em Pinheiros amanhã das 14 às 17h"'],
        accent: 'var(--chat-text-2)',
      },
      { kind: 'bot', typing: 1100, delay: 800, text: 'Entendi assim 👇' },
      { kind: 'info-card', delay: 400,
        title: 'Critérios captados',
        lines: [
          '📍 Pinheiros',
          '👥 4 pessoas',
          '📅 Amanhã (quarta · 23/05)',
          '⏰ 14:00 – 17:00',
        ],
      },
      { kind: 'bot', delay: 500, text: 'Tá certo? Posso buscar?' },
      { kind: 'quick-replies', delay: 400, items: ['Tá certo, buscar', 'Mudar algo', 'Cancelar'] },
      { kind: 'user', delay: 2200, text: 'Tá certo, buscar' },
      { kind: 'bot', typing: 1300, text: 'Achei 2 opções em Pinheiros que servem 🎯' },
      { kind: 'room', delay: 400, room: ROOMS.pinheiros },
      { kind: 'room', delay: 200, room: ROOMS.vila },
    ],
  },

  /* ─────────── W-02 — Mesa solo · crossell na confirmação ─────────── */
  {
    id: 'w02', p: 'W-02',
    title: 'Mesa solo · crossell',
    category: 'Ideação · em proto',
    summary: 'Ao confirmar sala, check para adicionar mesa individual por +1,25 créd. Total sobe de 21 para 22,25.',
    color: '#cadb66',
    startTime: { h: 11, m: 5 },
    steps: [
      { kind: 'user', text: 'quero reservar uma sala pra amanhã 14h no Tribbos' },
      { kind: 'bot', typing: 1100, text: 'Pode ser! Vou abrir a confirmação aqui 👇' },
      { kind: 'open-sheet', delay: 800, sheet: {
        title: 'Confirmar reserva',
        intro: 'Tribbos Coworking',
        subtitle: 'Sala de reunião 02 · 23/05 · 14:00–17:00',
        rows: [
          { label: '👥 Pessoas', value: '3 pessoas' },
          { label: '⏱️ Duração', value: '3h' },
          { label: '📍 Endereço', value: 'Av. M. Floriano P., 720' },
          { label: '💳 Total', value: '21 créditos', isTotal: true, bold: true },
        ],
        offer: {
          checkbox: true,
          emoji: '🪑',
          label: 'Add-on · crossell',
          title: 'Adicionar mesa individual',
          subtitle: 'Chegue mais cedo ou fique depois — mesa na área comum com café e Wi-Fi.',
          extraLabel: '+1,25 créd',
          totalWithOffer: '22,25 créditos',
        },
        cta: 'Solicitar reserva',
      }},
      { kind: 'flow-submitted', delay: 5000, label: 'Solicitar reserva' },
      { kind: 'bot', typing: 1100, text: 'Tudo certo! Reserva confirmada ✅\n\n🏢 **Tribbos** · sala 02 · amanhã 14h–17h\n🪑 Mesa individual inclusa\n\n💳 **22,25 créditos** debitados\n☕ Café na mesa te espera!' },
    ],
  },

  /* ─────────── P-20 — Onde meu time vai (espaços por data + colegas) ─────────── */
  {
    id: 'p20', p: 'P-20',
    title: 'Onde meu time vai',
    category: 'Coordenação de time',
    summary: 'Espaços agrupados por data, com fotos e nomes dos colegas confirmados em cada espaço e dia. Decida onde ir junto.',
    color: '#3a80ce',
    startTime: { h: 8, m: 40 },
    steps: [
      { kind: 'user', text: 'onde meu time vai essa semana?' },
      { kind: 'bot', typing: 1100, text: 'Dei uma olhada nas reservas do seu time 👀\n\nAgrupei por dia os espaços com mais gente confirmada — é só escolher onde ir junto 👇' },
      { kind: 'space-days', delay: 500,
        title: 'Seu time essa semana',
        subtitle: '3 dias com colegas confirmados perto de você',
        days: [
          {
            dow: 'QUA', dateNum: '17', label: 'Quarta · 17/06',
            note: '6 colegas confirmados',
            spaces: [
              {
                coworking: 'Tribbos Coworking', area: 'Centro', time: '10:00–17:00', credits: 7,
                recommended: true,
                action: 'Ir junto na quarta',
                people: [
                  { name: 'Joana Maciel', company: 'Acme', color: '#a768ff' },
                  { name: 'Pedro Silva',  company: 'Acme', color: '#3a80ce' },
                  { name: 'Marcelo Reis', company: 'Acme', color: '#fe8c14' },
                  { name: 'Bia Nunes',    company: 'Loomi', color: '#25c265' },
                ],
              },
              {
                coworking: 'Hub Pinheiros', area: 'Pinheiros', time: '09:00–15:00', credits: 7.5,
                action: 'Ir junto na quarta',
                people: [
                  { name: 'Rafael Dias', company: 'Loomi', color: '#ec4899' },
                  { name: 'Lia Costa',   company: 'Loomi', color: '#de6530' },
                ],
              },
            ],
          },
          {
            dow: 'QUI', dateNum: '18', label: 'Quinta · 18/06',
            note: '4 colegas confirmados',
            spaces: [
              {
                coworking: 'Vila Olímpia Hub', area: 'Vila Olímpia', time: '09:00–13:00', credits: 8.5,
                recommended: true,
                action: 'Ir junto na quinta',
                people: [
                  { name: 'Joana Maciel', company: 'Acme', color: '#a768ff' },
                  { name: 'Caio Mendes',  company: 'Acme', color: '#81c42b' },
                  { name: 'Bia Nunes',    company: 'Loomi', color: '#25c265' },
                  { name: 'Téo Ramos',    company: 'Nuvio', color: '#3a80ce' },
                ],
              },
            ],
          },
          {
            dow: 'SEX', dateNum: '19', label: 'Sexta · 19/06',
            note: '3 colegas confirmados',
            spaces: [
              {
                coworking: 'WorkBricks Itaim', area: 'Itaim Bibi', time: '14:00–18:00', credits: 9,
                action: 'Ir junto na sexta',
                people: [
                  { name: 'Pedro Silva',  company: 'Acme', color: '#3a80ce' },
                  { name: 'Marcelo Reis', company: 'Acme', color: '#fe8c14' },
                  { name: 'Téo Ramos',    company: 'Nuvio', color: '#a768ff' },
                ],
              },
            ],
          },
        ],
      },
      { kind: 'bot', delay: 600, text: 'Se topar algum, é só escolher que eu reservo o espaço pra você 💛' },
      { kind: 'quick-replies', delay: 400, items: ['Quarta no Tribbos', 'Quinta na Vila Olímpia', 'Ver próxima semana'] },
      { kind: 'user', delay: 2000, text: 'Quarta no Tribbos' },
      { kind: 'bot', typing: 900, text: 'Reservado ✅\n\n**Tribbos · Centro** · quarta 17/06 · 10h–17h\n💳 7 créditos debitados\n\nVocê vai estar com **Joana**, **Pedro**, **Marcelo** e **Bia** — boa quarta! 👋' },
    ],
  },
];

window.SCENARIOS = SCENARIOS;

})();
